### ISSUE TITLE
how to define "emacsclient -t" as khard's "editor"?

### ISSUE THREAD

**Issue by gour** [scheibler/khard#102]
Hello,

I'd like to use:

```
[general]
editor = emacsclient -t
...
```

in my _khard.conf_, but whatever I try I get:

```
Error in config file
Invalid editor path or executable not found.
```

Any hint?

**Comment by scheibler** [comment]
Currently the editor variable doesn't allow parameters. Instead the whole string is interpreted as
the editor name and you don't have installed an editor with the name ```emacsclient -t```.

I think, the easiest fix would be a small helper script. Let's name it start_emacsclient.sh:

```
#!/bin/bash
emacsclient -t "$1"
```

Assuming, that you open a text file in emacs with the -t parameter.

Then set the editor variable in the khard config file to the helper script path:

```
editor = ~/bin/start_emacsclient.sh
```

**Comment by gour** [comment]
> I think, the easiest fix would be a small helper script.

OK, I wasn't sure if there is some built-in way to do it...using helper script now. ;)
