### ISSUE TITLE
add a manpage

### ISSUE THREAD

**Issue by legrostdg** [scheibler/khard#104]
It would be cool to add a manpage to khard.

**Comment by Unip0rn** [comment]
As well as for the config file, too.

**Comment by lucc** [comment]
I will hijack this thread and extend the question a litte bit: We should restructure the way khard's user documentation is organized. Currently we have the help output and the README file. To me this division would make sense:
1. the README: should be smaller and just present the main features and idea of khard+instructions on installing and contributing (could be moved to a dedicated CONTRIBUTING file later)
2. the man page(s?): should contain most of the in depth documentation currently found in the README. If the examples and tips grow out of bounds they could be moved to the wiki.
3. the help output: is mostly good as it is right now, only that help output for subcomands doesn't work without a config file.

**Comment by lucc** [comment]
We could use sphinx to build all kinds of documentation.

**Comment by lucc** [comment]
We could also use github pages to serve the docs as our website: [official docs](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)

I think we can even use the sphinx docs for that. It looks like [khal](https://github.com/pimutils/khal) does that.

**Comment by jelmer** [comment]
It would be nice to have a manpage (regardless of other documentation); some distributions, e.g. Debian require a manpage for every binary.

**Comment by lucc** [comment]
@legrostdg I merged a man page in #201. I hope that covers the basics of this feature request. For further improvements to the documentation I opened #204. I invite everybody interested to join the discussion there.

**Comment by legrostdg** [comment]
It's great, thanks!
