### ISSUE TITLE
vobject#39 was closed, please update deps + release

### ISSUE THREAD

**Issue by matthiasbeyer** [scheibler/khard#108]
Hi.

https://github.com/eventable/vobject/issues/39 was closed and resolved by https://github.com/eventable/vobject/pull/49. Please update the dependency specification and release `0.11.4` with it, so we can update the nix package definition.

I will, for now, bring vobject as 0.9.2 into the scope of the nix package khard (at 0.11.3 then) until this is fixed.

---

Make sure to ping me if this is solved, so I can update the pkg.

**Comment by lucc** [comment]
The commit 9c12f1864c8afc8d8de4316d86c8f0823c5dc063 in the develop branch might be what you are looking for.

@scheibler do you need some help in order to prepare a release?

**Comment by scheibler** [comment]
Khard version 0.9.4 released

**Comment by scheibler** [comment]
Of course it's khard version 0.11.4

**Comment by scheibler** [comment]
Done.
