### ISSUE TITLE
Templates: Three or four 'y' for year?

### ISSUE THREAD

**Issue by thfi** [scheibler/khard#109]
I noticed that the .yaml fields in `test/template` as well as the 'original' file `template_for_contact_creation.yaml` contain the following line:

```yaml
#   vcard 3.0 and 4.0: yyy-mm-dd or yyyy-mm-ddTHH:MM:SS
```

The comment above recommends three `y` for the year, but shouldn't it be four?

**Comment by scheibler** [comment]
Of course. Thank you.
