### ISSUE TITLE
mutt use

### ISSUE THREAD

**Issue by Tonus1** [scheibler/khard#121]
Hi,

When I try to get an email adress in mutt, the output shows the full line and not just only the email.
Could it be changed ?

I tried :
```
set query_command= "/path-to/khard email --search '%s' | awk '{ print $NF }'"
```

```
set query_command= "/path-to/khard email '%s' | awk '{ print $NF }'"
```

```
set query_command= "/path-to/khard email --search '%s'"
```

with :
```
bind editor <Tab> complete-query
bind editor CT    complete
```

**Comment by scheibler** [comment]
Try to use:

```
set query_command= "khard email -p %s"
```

It seems, that you are using a rather old khard version (current is 0.11.4). Please consider an update first.

**Comment by Tonus1** [comment]
Thank you for your quick answer! 

I'll try that as soon as possible. 

Btw I think I've updated about last week. Anyway, will check that too. 

Regards 

⁣Tonus. ​

Le 24 févr. 2017 14:58, à 14:58, Eric Scheibler <notifications@github.com> a écrit:

**Comment by legrostdg** [comment]
@Tonus1 Can you close the issue?

**Comment by Tonus1** [comment]
Just started a new job, not much time these days, sorry. 

I'll close it tomorrow, promise 

⁣Tonus. ​

Le 1 mars 2017 16:08, à 16:08, legrostdg <notifications@github.com> a écrit:
