### ISSUE TITLE
sort accentuated characters wrong

### ISSUE THREAD

**Issue by legrostdg** [scheibler/khard#126]
khard sorts accentuated characters after all other characters. It should strip accents for the sort.

    $ khard
    1    Albert
    2    Eleanor
    3    Eugene
    4    Zakari
    5    Éric

    should be 

    $ khard
    1    Albert
    2    Eleanor
    3    Éric
    4    Eugene
    5    Zakari

**Comment by scheibler** [comment]
Should be fixed now. Please try out the develop branch to confirm.

**Comment by legrostdg** [comment]
It fixes the issue, thanks!
