### ISSUE TITLE
Search in email does not support accented character

### ISSUE THREAD

**Issue by nicoe** [scheibler/khard#129]
The command "khard email --parsable Céd" does not return any match while the command "khard email --parsable Ced" return a list of people matching with their first name "Cédric".

**Comment by scheibler** [comment]
I'am sorry but I can't reproduce that.

I've created a contact with the first name "Cédric" and an email address.
The command `khard email --parsable Céd` returns the created contact while `khard email --parsable Ced` finds nothing (everything as expected).

Could you pull the develop branch and try again? If the problem still occurs, please provide some additional information.

**Comment by nicoe** [comment]
I finally took some time to search the origin of the issue.
The contact do not define parts of the name but only the full name. Thus print_vcard do not output name related information and are not found by a simple search (but a strict search will find them).

So there is no bug per se but the difference in behaviour between the strict search and the full search in this specific case might be puzzling.

**Comment by scheibler** [comment]
Thanks for the input.

Now the print_vcard() function outputs the "fn" attribute if neither "n" nor "org" is present. That
should fix the different behavior of strict search vs. search in all fields.

But I still don't know how to edit contacts which only define "fn". At the moment the name fields in
the open contact template are empty. Therefore you would have to convert the contents of the "fn"
attribute manually.

**Comment by nicoe** [comment]
* Eric Scheibler  [2018-06-04 10:15 +0200]: 

>Thanks for the input.

You're welcome. Thank you for your work on khard.

>Now the print_vcard() function outputs the "fn" attribute if neither
>"n" nor "org" is present. That should fix the different behavior of
>strict search vs. search in all fields.

Well I am using 0.12.2, but anyway I fixed all my contacts which
defined only fn to specify also first name and last name.

>But I still don't know how to edit contacts which only define "fn".

I don't think there is a solution.
fn is about how the name should be shown, the part are about what
compose the name.

Some people might want to be called "John the mad dog Mills" while
their first and last name are just John and Mills.

That's why I would include in print_vcard also FN (even if the n is
specified) and the nicknames.

But I don't know there might be a good reason not to do so :).
