### ISSUE TITLE
Is the date format `yyy-mm-dd` or `yyyy-mm-dd`

### ISSUE THREAD

**Issue by DamienCassou** [scheibler/khard#135]
Everywhere in the code I see that dates (e.g., for the birthday) must be entered with only 3 digits for the year:

> vcard 3.0 and 4.0: yyy-mm-dd or yyyy-mm-ddTHH:MM:SS

Is that really how it should be done or is this a typo? I can send a PR if you want.

**Comment by scheibler** [comment]
Indeed, a typo. It's already fixed in the develop branch (see #109).

**Comment by DamienCassou** [comment]
I should have checked other issues better. Sorry for the noise.
