### ISSUE TITLE
Support 'anniversary' (vcard 4.0) or 'x-anniversary' (vcard 3.0 or earlier)

### ISSUE THREAD

**Issue by thfi** [scheibler/khard#138]
Similarly to `birthday` fields, `anniversary` fields should be supported.
To my knowledge, only vcard 4.0 knows this field type, but for earlier versions it was common to use a private extension named `x-anniversary`. A simple ISO date without time (i.e. `YYYY-MM-DD`) should be the only acceptable data format.

**Comment by scheibler** [comment]
Support for anniversary attribute added.
Please try out and tell me, if it suits your needs.

**Comment by thfi** [comment]
Yes, it is working for me. Thank you very much!
