### ISSUE TITLE
Add a way to export a specific .vcf file

### ISSUE THREAD

**Issue by DamienCassou** [scheibler/khard#139]
To facilitate [solving conflicts](https://github.com/pimutils/vdirsyncer/issues/642) between two contacts in vdirsyncer, it would be nice to be able to pass a .vcf file to `khard export` command.

**Comment by lucc** [comment]
@DamienCassou #151 was merged. Does that solve your request? Can we close this? What else would be needed?

**Comment by DamienCassou** [comment]
Thanks. I'm closing this ticket now and will reopen if needed.

**Comment by lucc** [comment]
closing as per above comment
