### ISSUE TITLE
khard rm --force

### ISSUE THREAD

**Issue by josephholsten** [scheibler/khard#140]
I am working on a way to use FZF to select items to edit, remove, merge &c with khard.

At the moment, I have a selection working well with this shell function:
```sh
# select cards with fzf, returning uids for each
function khard-fzf() {
    cs=$(
        khard list |
        sed 1d |
        fzf --multi --header-lines=1 |
        esed 's/^.*[[:space:]]+([^ ]+)[[:space:]]*$/\1/'
    )
    echo "$cs"
}
```
I'd expect to be able to run `khard-fzf | xargs khard rm -u`, but this requires me to confirm.

Would anyone else be interested in a such a flag?

**Comment by scheibler** [comment]
Should be working too.

**Comment by josephholsten** [comment]
https://github.com/scheibler/khard/commit/fbfdf7e14746a90d629b1b4c22e31ca0bddca258 LGTM
