### ISSUE TITLE
khard list --format="{uid} {n}"

### ISSUE THREAD

**Issue by josephholsten** [scheibler/khard#141]
I am working on a way to use FZF to select items to edit, remove, merge &c with khard.

At the moment, I have a selection working well with this shell function:
```sh
# select cards with fzf, returning uids for each
function khard-fzf() {
    cs=$(
        khard list |
        sed 1d |
        fzf --multi --header-lines=1 |
        esed 's/^.*[[:space:]]+([^ ]+)[[:space:]]*$/\1/'
    )
    echo "$cs"
}
```
That last `sed -E` is pretty gross, and probably error prone. It would be really useful to be able to specify the order of the fields, or otherwise have UID in a known position so I could use a simple `awk '{print $2}'` or similar.

Would anyone else be interested in a such a flag?

**Comment by scheibler** [comment]
I've added the --parsable parameter to the list action (analog to email and phone actions).

```
khard list --parsable
```

Result:

```
UID\tContacts name\tName of address book
```

Please have a look into the develop branch and tell me, if this suits your needs.

**Comment by josephholsten** [comment]
Sounds great, I'll look into it this evening!

**Comment by josephholsten** [comment]
Think we could include the `vcard.get_email_addresses()` as well? It's especially convenient when I think of someone by their username more than their given name ;-)

A part of me also wants this to denormalize records with multiple emails into multiple rows, but that would bust use cases like `| wc -l` and probably other reasonable things.

**Comment by scheibler** [comment]
In your initial post you requested a clean way to query the uid of a contact. Now you could do something like:

```
for uid in $(khard ls --parsable [NAME OR SOMETHING ELSE TO SEARCH FOR] | cut -d$'\t' -f1)
do
    khard rm --force --uid $uid
done
```

Or you could remove them directly:

```
khard rm --force [NAME OR SOMETHING ELSE TO SEARCH FOR]
```

Same for email addresses:

```
for uid in $(khard ls --parsable [NAME OR SOMETHING ELSE TO SEARCH FOR] | cut -d$'\t' -f1)
do
    khard email --parsable --remove-first-line --uid $uid | cut -d$'\t' -f1
done
```

or without the ls command:

```
khard email --parsable --remove-first-line [NAME OR SOMETHING ELSE TO SEARCH FOR] | cut -d$'\t' -f1
```

Why do you need the email addresses in the parsable list output? Could you provide some more information please?

**Comment by josephholsten** [comment]
good point, I was overthinking this. The implementation does what's needed, and if I want more info exposed in a selector, I can easily map it as with your first email example.

LGTM!
