### ISSUE TITLE
Add documentation on how to setup a CardDAV server

### ISSUE THREAD

**Issue by stevenroose** [scheibler/khard#143]
I can't find it anywhere. The example config file uses `path=`, I guess that's for local address books. How to create a remote one? `khard abooks --help` also doesn't help. I already have a CardDAV setup, so I don't need davcontroller to create one.

**Comment by stevenroose** [comment]
I found the vdirsyncer section. So khard doesn't support remote address books itself?

**Comment by scheibler** [comment]
Yes, the general idea is, that you sync your address books with vdirsyncer and then access them locally with khard.
