### ISSUE TITLE
 mutt add sender e-mail addresses to the addressbook from pager using 'A'

### ISSUE THREAD

**Issue by jasonsmith0** [scheibler/khard#16]
Hi,

Is it possible with khard to  add sender e-mail addresses to the addressbook from pager using 'A'?

In mate one can do this with:
```
macro index,pager A \
    "<pipe-message>mates add | xargs mates edit<enter>" \
    "add the sender address"
```
With abook
```
macro pager A |'abook --add-email'\n
```
Hoping one can do the same with khard somehow?

**Comment by jasonsmith0** [comment]
If so, perhaps it can be added to the documentation in the mutt section.

**Comment by scheibler** [comment]
I've implemented your feature request. Please check out the latest commit and try it out.

Add the following to your mutt config:

```
macro index,pager A \
    "<pipe-message>khard add-email<return>" \
    "add the sender email address to khard"
```

Regards

**Comment by jasonsmith0** [comment]
Awesome - thanks!
