### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-eqv4yo2m/vobject

### ISSUE THREAD

**Issue by clauseggers** [scheibler/khard#17]
I'm getting this error `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-eqv4yo2m/vobject` when running `pip install --user khard`
Full output:
```
Collecting khard
  Downloading khard-0.4.0.tar.gz (5.0MB)
    100% |████████████████████████████████| 5.0MB 67kB/s 
Requirement already satisfied (use --upgrade to upgrade): configobj in /usr/lib/python3.4/site-packages (from khard)
Collecting vobject (from khard)
  Downloading vobject-0.6.6.tar.gz (53kB)
    100% |████████████████████████████████| 57kB 2.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-pofw42eb/vobject/setup.py", line 31, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-build-pofw42eb/vobject/ez_setup/__init__.py", line 94
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pofw42eb/vobject
```

**Comment by untitaker** [comment]
You're using the wrong Python, you need Python 2.

**Comment by clauseggers** [comment]
Ahh, yes that did the trick. Thanks.

**Comment by heyi244573246** [comment]
I don't konw why,It's give me this issue when I used Python3.6 ,I charge my Python to 2.7,It's give me same again issue. could you give me some ways?

**Comment by scheibler** [comment]
Meanwhile khard requires python3 to work. I don't have a python 3.6 environment so I can't confirm
your issue there. Please try out python 3.5 - that's what I'am currently using.

**Comment by heyi244573246** [comment]
Thank you for your answer, I will try it

**Comment by sugaobo2** [comment]
I got the same issue when i exec "pip install virtualenvwrapper ".I have verified pip version,like that :"pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)". I don't know why.

**Comment by scheibler** [comment]
You are still useing Pip and Python 2.7. Please try to follow the installation instructions from the readme file:

```
sudo pip install virtualenv
mkdir ~/.virtualenvs
virtualenv -p python3 ~/.virtualenvs/khard
~/.virtualenvs/khard/bin/pip install khard
mkdir ~/.virtualenvs/bin
ln -s ~/.virtualenvs/khard/bin/khard ~/.virtualenvs/bin
```

More information about virtualenv at http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by WFnian** [comment]
you are right.
`sudo pip install virtualenv
mkdir ~/.virtualenvs
virtualenv -p python3 ~/.virtualenvs/khard
~/.virtualenvs/khard/bin/pip install "what you want to download, such as wxpy,,,,"`

**Comment by WFnian** [comment]
you are right.
`sudo pip install virtualenv 
mkdir ~/.virtualenvs 
virtualenv -p python3 ~/.virtualenvs/khard
~/.virtualenvs/khard/bin/pip install "what you want to download, such as wxpy,,,,"`

**Comment by WFnian** [comment]
`sudo pip install  \nvirtualenv mkdir ~/.virtualenvs virtualenv -p python3 ~/.virtualenvs/khard ~/.virtualenvs/khard/bin/pip install \n"what you want to download, such as wxpy,,,,"`

**Comment by SamElvi** [comment]
when i used this command 'pip install Scrapy'
i got this error : 
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/b1/4jz1mgzn7ks0s6_4272tgdbw0000gn/T/pip-build-lCKyhy/Twisted/

**Comment by scheibler** [comment]
I'am sorry but it seems to me, that your issue has nothing to do with khard.

Please head over to https://github.com/scrapy/scrapy

**Comment by Apokar** [comment]
@SamElvi  Did u solve this error ? I got the same error when I 'sudo pip install Scrapy' Can u help me ?
