### ISSUE TITLE
last names starting with non-capital letters are added as part of first name

### ISSUE THREAD

**Issue by dvzrv** [scheibler/khard#172]
When creating a contact that has a "special" last name, such as "von Something", the "von" part will be added as part of the first name.
That's not correct though and also breaks sorting.

The "von", "zum" or "zur" name prefixes are (still) pretty common in Germany, but there are other use cases with latin-American, French or Spanish names (e.g. "de" "de la").

It would be awesome if this could be fixed!

**Comment by lucc** [comment]
Can you please specify what you did exactly? I can not reproduce this with a quick test. Which version do you use/which branch are you on? 

I did this in the shell: 
```sh
$ export KHARD_CONFIG=test/fixtures/minimal.conf # with editor and merge editor adjusted
$ printf 'First name: Foo\nLast name: von Bar\n' | khard add -a test
Creation successful

Name: Foo von Bar
Address book: dropin
Miscellaneous
    UID: t9bo8ud06exx18qnar01kdkhhvb1mcrel7tl
$ khard export -a test foo von bar | grep -i name
# Name: Foo von Bar
# name components
#   First name : name1
#       - name2
#       - name3
#   Last name  : name4
First name : Foo
Last name  : von Bar
# nickname
Nickname : 
```

**Comment by dvzrv** [comment]
@lucc sorry, could've added that earlier... :>

It's khard 12.2

khard.conf:

```
[addressbooks]

[[contacts]]
path = ~/.contacts/contacts

[general]
editor = vim
merge_editor = vimdiff
default_action = list
show_nicknames = yes

[contact table]
sort = last_name
group_by_addressbook = no
show_nicknames = yes
show_uids = yes

[vcard]
preferred_version = 3.0
private_objects = Jabber, Ring, Twitter

```

I have a contact whose name has the last name "von XYZ", but the "von" is showing up as part of the First name, when I do a khard edit "von XYZ". When I change that contact and save, it will still be saved as "First name von" "Last name" (leading to no change).

However, doing your test I get the same results as you! So maybe this has something to do with existing contacts? oO

**Comment by dvzrv** [comment]
Okay lol... it gets weirder.
If I remove the "von", save the contact, reopen and prefix the Last name with the "von" it finally sticks!

**Comment by lucc** [comment]
If it is about existing contacts you can close this I think. Otherwise we would need *detailed* instructions to reproduce this.

**Comment by dvzrv** [comment]
I guess so, too!
If someone else encounters this issue, the workaround/fix is to remove the last name prefix, save and then add it. Probably.
