### ISSUE TITLE
"phone" command does not yield all phone numbers

### ISSUE THREAD

**Issue by madduck** [scheibler/khard#173]
Alex has a few phone numbers:
```
% khard export alex | grep -A5 'Phone :'
    VOICE, CELL, TEXT, pref=1 : +64 21 xxxxxxx
    VOICE, CELL, TEXT, pref=2 : +49 176 xxxxxxxxx
    VOICE, MSG, pref=2        : +49 89 xxxxxxxx
    VOICE, pref=2             : sip:xxx@xxxxxxx.net

```

However, when I invoke `khard phone`, I only see the last:
```
% khard phone alex
Name                          Type             Phone                   
XXX, Alex    VOICE, pref=2    sip:xxx@xxxxxxx.net
```

Instead, I'd expect all four entries to be shown, sorted in order of their preference fields.

**Comment by lucc** [comment]
@madduck this seems to be in v0.13 can you try that and maybe close this issue?

**Comment by madduck** [comment]
I just tried khard 0.13.0 (from Debian), and I could not discern any difference in the output, unfortunately. So no, it doesn't seem fixed, @lucc.

**Comment by lucc** [comment]
Do you have a vcard to test this with?

**Comment by madduck** [comment]
My own, which you can get from https://scratch.madduck.net/contacts__Krafft_Martin.vcf and please let me know once you have it so that I can remove it again.

**Comment by lucc** [comment]
@madduck I got your file thank you. But I don't get your bug (or I don't understand it):
```sh
git checkout v0.13
khard --version
# Khard version 0.13.0
mv contacts__Krafft_Martin.vcf test/fixture/foo.abook
sed -i -e s/meditor/vimdiff/ -e s/editor/vim test/fixture/minimal.conf
khard -c test/fixture/minimal.conf phone martin | wc -l
# 8
khard -c test/fixture/minimal.conf phone -p martin | wc -l
# 7
khard -c test/fixture/minimal.conf filename martin | xargs cat | grep -c '^TEL'
# 7
```
And with `export` I also see all seven numbers. Can you please check again and try to pin down the problem some more. I can not reproduce it like this.

**Comment by madduck** [comment]
I cannot reproduce the problem now anymore. argh! Anyway, I guess that's good news. Thanks for sticking with me.
