### ISSUE TITLE
Confusing subcommands

### ISSUE THREAD

**Issue by madduck** [scheibler/khard#174]
It's sometimes very confusing that a plain search is initiated without a subcommand, whereas e.g. `khard search` actually searches for contacts matching `/search/`.

There is no `search`, though this should probably be introduced as an alias for `list`.

Finally, please consider removing `default_action` and treating it an error if no action has been specified, similar to how `khal` does it now.

**Comment by lucc** [comment]
We could also make default_action optional and not default to "list" but require an action from the command line in this case. That would mean there only exists a default action if it is specified in the config (= the user wants it).

**Comment by lucc** [comment]
@madduck what do you think about #213?

**Comment by madduck** [comment]
Looks good, @lucc. Thanks for working on this. In general, I think simpler would be better, but this is most compatible with the status quo.

**Comment by lucc** [comment]
I merged #213 so we can try it for a while and decide if we want to make a breaking change and never set "list" as the default or not.
