### ISSUE TITLE
khard mv very slow

### ISSUE THREAD

**Issue by 0-wiz-0** [scheibler/khard#178]
I'm using `khard` to move `.vcf` files from one local directory to another.
It takes 10 seconds to move one vcard (of size <1kB):
````
time khard mv -u FAD -A old
Move contact $CONTACT from address book default
Moved contact $CONTACT from address book default to old
khard mv -u FAD -A old  5.81s user 3.87s system 99% cpu 9.734 total
````
For comparison:
````
time mv -i ~/personal/contacts/default/$UID.vcf ~/personal/oldcontacts 
mv -i  ~/personal/oldcontacts  0.00s user 0.00s system 68% cpu 0.002 total
````

**Comment by lucc** [comment]
This is related to #103 because the copy and move commands parse all vcards in the target address book to check if the new card is already present.

**Comment by lucc** [comment]
If this is still an issue we have to find out where the time is spend and how we can reduce it. See the discussion in #103 for details and examples how that works. 

Otherwise we could close this issue.
