### ISSUE TITLE
Support XDG Directories for configuration files?

### ISSUE THREAD

**Issue by darnir** [scheibler/khard#181]
I'd like to use `khard`, but currently I use it by always having to call it with the `-c` parameter since I prefer keeping all my configuration files in a single directory.

Would it be possible for you to add a fallback to check at `$XDG_CONFIG_HOME/khard/config` in case the the config file is not found at `~/.config/khard/khard.conf`

**Comment by scheibler** [comment]
If I define:

```
export XDG_CONFIG_HOME="$HOME/example"
```

in my preferred shell then khard expects its config file at `$HOME/example/khard/khard.conf`.

Do you use an old version of khard where the xdg support was not implemented yet? The current khard
version is 0.12.2. If so please update and try again.
