### ISSUE TITLE
ERROR:root:454 of 463 vcard files of address book *** could not be parsed

### ISSUE THREAD

**Issue by kflak** [scheibler/khard#184]
Hi,

Suddenly getting the above error, after khard has been working flawlessly for a long time. I don't think I have done anything radical to change anything...
Output from 
`khard --debug`
```
[--- cut ---]
At line 15: In transformToNative, unhandled exception on line 15: <class 'ValueError'>: invalid literal for int() with base 10: '4-' (<REV{}2016-04-30T15:33:00Z>)
ERROR:root:454 of 463 vcard files of address book woelkli could not be parsed
[---cut---]
```
I am not enough of a python buff to know what I need to install to make this work, or what has broken it. I am running on Arch Linux.

```
$ khard -v
Khard version 0.12.2
$uname -r
4.9.84-rt62-1-rt-lts
```
Best,
K

**Comment by benoliver999** [comment]
OK I think I am getting this too.

The output inludes the affected files. I noticed the line that was causing the breakage was `REV`

I had a line a bit like this:

    REV:2018-06-07-T081353Z

So I went in and changed it to:

    REV:20180607T081353Z

And it fixed the error.

HOWEVER I am getting a related issue when creating a new contact:

    vobject.base.NativeError: "In transformFromNative, unhandled exception on line None <class 'AttributeError'>: 'str' object has no attribute 'tzinfo'"

The editor opens, I set the data but it doesn't save due to this error.

System:

    Khard version 0.12.2
    Python 3.6.6
    4.17.5-1-ARCH

**Comment by benoliver999** [comment]
Possibly related to this: https://github.com/eventable/vobject/issues/120

**Comment by benoliver999** [comment]
OK I can confirm that rolling back to `python-vobject-0.9.5-4-any.pkg.tar.xz` did the trick, but it's obv. a temporary fix

**Comment by protist** [comment]
I'm also using Arch Linux, and can also confirm that reverting from python-vobject 0.9.6-1 to 0.9.5-4 fixes it for me.

**Comment by protist** [comment]
Also, as per the linked bug report, I can confirm that rolling back that [commit](https://github.com/eventable/vobject/commit/6462c67320e387ebf49f769bbcb2933d0583860f) fixes khard. This is equivalent to just replacing `/usr/lib/python3.6/site-packages/vobject/vcard.py` with the old version from 0.9.5-4 in Arch.

**Comment by benoliver999** [comment]
I think khard needs to change to the non-expanded ISO format eg:

    19961022T140000

It is mentioned in RFC6350 that this is the only allowed format.

**Comment by dvzrv** [comment]
sorry, but I had to update python-vobject for Arch. Sadly the whole shebang with dateutil and vobject is in a really weird state right now... lots of constant breakage with khal and vdirsyncer, too :(

**Comment by benoliver999** [comment]
Yeah it's broken usage with davdroid too. They use a lib called ez-vcard and I've asked about a change over there.

https://github.com/mangstadt/ez-vcard/issues/89

I would go and moan over at vobject but frankly they are only following the standard as it has been set out.

**Comment by benoliver999** [comment]
SO it turns out you _should_ use the extended date format if you are following vcard 3.0 (RFC 2426).

If that is what khard does, rather than RFC 6350, then we should do nothing here an get vobject to support both.

**Comment by wpercy** [comment]
okay, because this broke so many other implementations I've decided to push out a fix that, while not in 100% alignment with the spec, should resolve these issues. vObject 0.9.6.1 should resolve these issues.

**Comment by dvzrv** [comment]
@wpercy thanks, 0.9.6.1 fixes this for me!
I shipped this to Arch Linux [community].

**Comment by kflak** [comment]
Fixed! Thanks :-)

**Comment by potuz** [comment]
Installing 0.9.6.1 allows me to parse existing contacts but I still hit this issue when creating new contacts.

**Comment by quite** [comment]
All good here too, it seems to me this can be closed.
