### ISSUE TITLE
merge_editor does not work with nvim

### ISSUE THREAD

**Issue by nielsk** [scheibler/khard#190]
There is no vimdiff, when one is using neovim. When I use 
merge_editor = "/usr/bin/nvim -d"

 then I get the message 
Invalid merge editor path or executable not found.

When I set an alias for vimdiff (alias vimdiff = /usr/bin/nvim -d) it works in the command line but khard gives me also the error
Invalid merge editor path or executable not found.

I'd expect that both should work

**Comment by lucc** [comment]
Aliases will never work outside of your running shell sessinon. They are only meant for *interactive* shell usage. They differ fundamentally from external commands.

The merge editor option currently only supports a single executable *without options*. The simplest solution is to create a wrapper script for `nvim -d`. The nice solution would be a PR to fix it here ;)
