### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by pprw** [scheibler/khard#195]
I cannot sync some contacts (not all).

This is an example of a vcard which does not sync.

What is the problem?

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.2//EN
UID:bf3lycta2gmsk1ts57owath965h38709zoyu
EMAIL;TYPE=home:email@email.org
FN:Name firstname
N:Name;firstname;;;
REV:20180923T191324Z
TEL;TYPE=cell;VALUE=URI:67545678
CATEGORIES:badsdsq
END:VCARD

```

```
$ khard
Address book: contacts
Traceback (most recent call last):
  File "/usr/bin/khard", line 11, in <module>
    load_entry_point('khard==0.12.2', 'console_scripts', 'khard')()
  File "/usr/lib/python3/dist-packages/khard/khard.py", line 1670, in main
    list_subcommand(vcard_list, args.parsable)
  File "/usr/lib/python3/dist-packages/khard/khard.py", line 890, in list_subcommand
    list_contacts(vcard_list)
  File "/usr/lib/python3/dist-packages/khard/khard.py", line 338, in list_contacts
    sorted(phone_dict.get(first_type))[0]))
IndexError: list index out of range


```

**Comment by pprw** [comment]
It was the cell line (incorrect format). Anyway khard should not stop listing contacts for one misformated cell line (it makes hard to identify the problematic contact).

So this is kind of a bug report.

**Comment by lucc** [comment]
Thanks @pprw  for the report. Sorry we didn't help you debug this.

@scheibler we should address this after you made a release and #169 is merged. It would be beneficial if parse errors would just produce an error or warning in the output but not stop the parsing altogether. I remember that I did some error handling with the logger in #169 but I don't think it covers all parsed properties already.

Let's leave this open for reference.

**Comment by scheibler** [comment]
I've fixed this a few days ago but forgot to push and announce. This error indeed came from a misformatted phone number.

Nevertheless I agree, the error handling could be improved.

**Comment by cl-parsons** [comment]
I had a problem with ";VALUE=URI:tel" in my vcard. A small sed script fixed this, and then I updated all my computers to fix the broken vcards.

``
 sed -i 's/;VALUE=URI:tel//' ~/addressbooks/contacts/*
``

**Comment by lucc** [comment]
I have added a test case for this.  Any further error handling problems should be reported in a new issue.
