### ISSUE TITLE
Print out mailing addresses

### ISSUE THREAD

**Issue by einveru** [scheibler/khard#196]
Would it be possible to have Khard list the mailing addresses of all contacts, much like the phone list or the email list? As I am building up my address book and setting up cardDav currently, having a way to list all my contact's physical addresses might prove useful. (Xmas cards, mailing lists, etc)

**Comment by scheibler** [comment]
I've added an action for postal address output.

Show post addresses with: `khard post`

Please check out the develop branch and give it a try.

**Comment by einveru** [comment]
Works beautifully. Thank you. Perhaps a space or some sort of line between each entry for readability, if possible, but that's not incredibly important.
