### ISSUE TITLE
To split or not to split search terms?

### ISSUE THREAD

**Issue by lucc** [scheibler/khard#198]
The search term provided on the command line are translated into a regex by joining the individual strings with `.*`. Spaces *inside* an argument are not treated specially so a call like `khard ls "foo bar"` searches for the regex `foo bar` whereas a call like `khard ls foo bar` searches for the regex `foo.*bar`.

This might create confusion or trouble when some other program (like mutt) does not give us enough freedom to choose what we want to call (this was previously discussed in https://github.com/scheibler/khard/pull/192#issuecomment-449659327).

We could introduce a new behaviour and just split the arguments at whitespace before joining them with `.*`. This would only match more as spaces are obviously matched by `.*`.

We could
1. Add yet another command line option `--split-at-whitespace` to toggle the behaviour.
2. Or just make it the default without any new options (so the old behaviour is essentially "lost")

I would vote for 2 because it is simpler and I can not see any trouble it introduces. What do others think?

**Comment by d7415** [comment]
On a linux (or similar) shell I expect items in quotation marks (or escaped spaces) to be treated literally. I think splitting arguments in quote marks is likely to cause more confusion, though probably only at edge cases. I think is more likely to show up if a user keeps extensive notes in the Note section of contacts.

Unlikely edge case: John Smith and Jo Mit. with the new behaviour John will always appear when I'm searching for Jo.

**Comment by lucc** [comment]
This is obsolete as we do not use regex for searches internaly any more.
