### ISSUE TITLE
Khard crashes with vdirsyncer contacts

### ISSUE THREAD

**Issue by libre-man** [scheibler/khard#20]
Khard crashes with every action with this traceback. It looks like one of my contacts has multiple addresses and khard does not expect that.

```python
Traceback (most recent call last):
  File "/usr/local/bin/khard", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/khard/khard.py", line 239, in main
    vcard_list = Config().get_vcard_objects(selected_addressbooks, args.sort, args.reverse, args.search, False)
  File "/usr/local/lib/python2.7/dist-packages/khard/config.py", line 137, in get_vcard_objects
    if regexp.search(vcard.print_vcard()) != None:
  File "/usr/local/lib/python2.7/dist-packages/khard/carddav_object.py", line 441, in print_vcard
    if self.get_post_addresses().__len__() > 0:
  File "/usr/local/lib/python2.7/dist-packages/khard/carddav_object.py", line 345, in get_post_addresses
    "street_and_house_number":child.value.street.encode("utf-8"),
AttributeError: 'list' object has no attribute 'encode'
```

Edit after some more looking into it, it seems that if there is a comma in the address field khard will not work.

**Comment by scheibler** [comment]
In general khard is able to deal with multiple addresses. The error message reports, that the street
value for one of your addresses is a list instead of a string. So the encoding function fails. This
also could happen at a contact with only one address.

Without further data I can't figure out, what's going wrong.  Therefore it would be very helpful, if
you could find and upload the concerning contact in an anonymized form.

Regards
Eric

**Comment by libre-man** [comment]
This Vcard does not work, but does if there are no comma's in the address field. (the contact was made on the contacts app in Android 5.1.1)

I fixed it (for me) by letting get_post_addresses check if child.value.street was a list and if it was joining it with a comma. That works but is not the nicest way to do it I guess.
```vcard
BEGIN:VCARD
VERSION:3.0
X-ANDROID-CUSTOM:vnd.android.cursor.item/nickname;[REDACTED];;;;;;;;;;;;;;
X-RADICALE-NAME:6a9f3951-72ac-4f4f-a22d-1e72a45d8931
X-PRODID:ez-vcard 0.9.6
X-DAVDROID-STARRED:1
UID:168e6df8-6f8e-4334-9cb3-1e942364f0f5
FN:[REDACTED]
N:[REDACTED];;;
TEL;TYPE=cell,pref:+31651220043
EMAIL;TYPE=work,pref:[REDACTED]
ADR;TYPE=home:;;Street\, Postcode\, City;;;;
LABEL;TYPE=home:Street\, Postcode\, City
URL:[REDACTED]
BDAY:[REDACTED]
PHOTO;ENCODING=b;TYPE=jpeg:[REDACTED]
PRODID:DAVdroid/0.8.2 (ez-vcard/0.9.6)
REV:20150810T151034Z
END:VCARD
```

**Comment by scheibler** [comment]
Your contacts application doesn't comply with the [vCard
standard](https://tools.ietf.org/html/rfc6350#section-6.3.1). The post address field should be
formatted like this:

```
ADR;TYPE=home:;;Street and house number;City;Region;Postcode;Country
```

But in your case it's all written into the street and house number field.

I fixed the error like you've suggested so khard can parse these contacts too. For testing check out
the master branch again. If you want, you could correct the addresses manually by using khard's
modify command.

Regards
Eric
