### ISSUE TITLE
editor/merge_editor should have argument options

### ISSUE THREAD

**Issue by cweagans** [scheibler/khard#206]
Many editors won't work with khard unless you can pass arguments to the editor (for instance, with vscode, `--wait` is necessary). The existing validation for editor and merge_editor seems fine, so maybe two new config options would fix this in a nice way? `editor_args` and `merge_editor_args`?

If I make a PR for this, will you accept it?

**Comment by lucc** [comment]
You can simply write a small shell script to pass the correct options to your editor.

**Comment by cweagans** [comment]
I know I _can_ write a small shell script, but that's kind of a hack given how common it is for an editor to need an option like this. Off the top of my head, at least vscode, textmate, gvim, and sublime text need this option.

**Comment by lucc** [comment]
@cweagans what do you think about #214? I noticed that it is not even a breaking change (as long as people don't have commas in their editor names or paths).

**Comment by cweagans** [comment]
I think that'd work for pretty much any case I'd need in my setup!
