### ISSUE TITLE
support for Claws-mail

### ISSUE THREAD

**Issue by gour** [scheibler/khard#21]
Hello,

at the moment I use Emacs/Gnus/org-mode for my email as well as to keep my calendars/contacts in sync with my Android phone via ownCloud server, but consider to switch back to Vim/Claws and I'm excited after seeing khard/khal aps, so I wonder if you have considered to add some import/export support for Claws' addressbook so that one can use vdirsyncer to sync contacts with the phone?

**Comment by untitaker** [comment]
Not sure what you're asking for, but I think you can use `singlefile`-storage from vdirsyncer in combination with "new VCard" from Claws' addressbook.

**Comment by gour** [comment]
But, afaict, that would just sync contacts *to* Claws, but not *from* it, right?

I'll also ask on Claws-list since, afaik, Claws supports only export/import of LDIF format. Other options are either export-only or import-only... :-(

**Comment by untitaker** [comment]
I don't know, but it's likely that it works both directions.

**Comment by gour** [comment]
> I don't know, but it's likely that it works both directions.

I don't think so...most of the utilities within Claws' addressbook is import-only.

Otoh, Claws' "native" format is (simple) XML, so the easiest way would be to add support for it?

**Comment by untitaker** [comment]
Ah I see, the addressbook is actually read-only then.

**Comment by untitaker** [comment]
@gour I'm still not sure about your goals. Are you trying to just import/export data from Claws to khard, or actually sync your server with Claws?

**Comment by gour** [comment]
> I'm still not sure about your goals. Are you trying to just import/export data from Claws to khard, or >actually sync your server with Claws?

Let me say that I've found that khard is terrific piece of software (didn't have time to try khal yet), but I really like such simple & powerful tools so it was not hard for me to decide to leave Emacs/Gnus/org-mode and go back to Vim/Claws/...

So, I want to sync my contacts between my Android phone and the desktop which is already possible by using khard/vdirsyncer via ownCloud.

But I'd like to be able to take advantage of my contacts within my mailer - Claws - as well.

So, I'm going to fill feature request to Claws devs to provide import/export facility for handling *.vcards.

> In the latter case it might make sense to refile this against vdirsyncer.

It looks you're right that this is, maybe, not issue for khard sinc khard handles *.vcard and it is more natural for Claws to be able to import/export *.vcard than adding Claws' addressbook (XML) support to khard.

**Comment by coachshea** [comment]
As I understand it, claws can import vcards to the address book (although manually not through a synchronization mechanism), but I'm not sure if it can export. 
I know people generally hate when they get the advise I'm about to give, but being the you are so comfortable with command-line tools like khard and khal, have you considered using mutt as your email client. It takes a little more work to get started, for sure, but it can interop with these tools (and any future tools) through stdin, stdout mechanisms. Offlineimap, which was the inspiration for vdirsyncer, can be used to sync the mail just like vdirsyncer. It might be worth at least checking out.

**Comment by untitaker** [comment]
I agree with John that mutt offers better integration with other CLI scripts,
but at the same time one has to keep in mind that mutt's learning curve is not
comparable with GUI clients, and that this learning curve is only worth it for
people who use email very intensively.

You have several options:

* You can use `xdg-open mailto:...` to launch Claws from the command line
  with a specific email address. This might help you integrate Claws Mail with
  khard, although this is suboptimal because Claws' own addressbook is
  certainly better integrated with Claws itself.

* You can wait for Claws to be able to sync with VCard files. There might be an
  extension out there that already does that.

* You can look for another GUI client. Last time I checked, Gnome Contacts was
  very good at integrating with CardDAV and VCard.

**Comment by gour** [comment]
> As I understand it, claws can import vcards to the address book (although manually not through a synchronization mechanism), 

I do not see it, only ability to create new vcard.

> but I'm not sure if it can export.

Nope. LDIF is, afaict, the only export facility.

> I know people generally hate when they get the advise I'm about to give, but being the you are so >comfortable with command-line tools like khard and khal, have you considered using mutt as your >email client. It takes a little more work to get started, for sure, but it can interop with these tools (and >any future tools) through stdin, stdout mechanisms. 

No problem with advises...however I use Linux since '99 and tried all them major mailers...started with Pine, used Evolution, mutt, spent some time with Gnus and recently with mu4e, but I must say that Claws is simply my favourite. It works well via keyboard, has supprt for NNTP - mutt, afaik, still did not integrate nntp patch - which is very handy that majority of mailing lists I follow via Gmane, it has RSS reader included as plugin, powerful search (better than mairix) etc.

If I would not have need for e.g. nntp, than mu4e would be quite good.
 
> Offlineimap, which was the inspiration for vdirsyncer, can be used to sync the mail just like >vdirsyncer. It might be worth at least checking out.

At the moment I use offlineimap to 'convert' my Gnus/maildir mail into Claws MH. Otoh, when using mu4e, I found that mbsync works better than offlineimap.

**Comment by untitaker** [comment]
>I do not see it, only ability to create new vcard.

If you point that dialog to an existing file, claws will pick the contacts in it up.

**Comment by gour** [comment]
> You can wait for Claws to be able to sync with VCard files. There might be an extension out there that already does that. 

Well, if Claws would only have import/export facility for vcards, that would be enough and I would not mind to e.g. periodically export my contacts from Claws to khard, sync and then re-import into Claws.

>  You can look for another GUI client. Last time I checked, Gnome Contacts was very good at >integrating with CardDAV and VCard.

That goes via Evolution, iirc, and I simply do not trust it as my mailer...

**Comment by coachshea** [comment]
This is from the claws mail user manual in the address book section:

 
  It is arranged in different sections: the "Address Book" and its 
  subsections, which contain the contacts that you added locally; the vCard 
  sections, which contain imported vCards;

This certainly seems to suggest that you can import vCards. However, right 
below that in the section on importing/exporting (in which section nothing
about exporting is mentioned), it doesn't mention vCards at all. Go figure.

**Comment by untitaker** [comment]
I've tried it, it's read-only.

**Comment by untitaker** [comment]
The original feature request belongs into vdirsyncer (see untitaker/vdirsyncer#314), I think this should be closed.
