### ISSUE TITLE
man page not built/installed by default

### ISSUE THREAD

**Issue by 0-wiz-0** [scheibler/khard#218]
The 0.14.0 changelog mentions that a man page was added. I see it in `doc/source/manpage.rst`, but it is not built or installed by default, and I couldn't come up with the magic incantation to build it.

Could you please hook it into the build by default, or at least when sphinx is found on the system?
Thank you.

**Comment by lucc** [comment]
It can be build with the makefile in the doc directory. You could run `make -C doc man` from the root of the project. I think that is the standard sphinx way as this makefile was created by sphinx.

I am not sure where I should run the makefile/sphinx in the normal installation process. I assume package maintainers can run the makefile directly.  As for people installing via pip or the setup.py file directly maybe something like [this](https://stackoverflow.com/questions/28720624/install-sphinx-compilated-doc-from-setup-py)? Do you have experience with such stuff? How do you install khard?

**Comment by 0-wiz-0** [comment]
Hm, I had tried that (`cd doc && make man`), but it doesn't work with BSD make, it needs GNU make.

I'm installing the rest of the software with `python3.7 setup.py build` and `python3.7 setup.py install` and it would be nice if that would already install the man page as well, but I can live with this version as well. (I'm packaging for pkgsrc, in case it matters.)

**Comment by lucc** [comment]
What is BSD make doing differently? Is it only a minor change to fix the makefile? 

I am not sure if installing manpages with `python setup.py install` makes sense as one could also install python packages into `~/.local` or a pyenv. And neither is in any `$MANPATH` I think.

Building might make sense though. Although all other data that `python setup.py build` generates is in `build/`.  Not sure what is the right way to solve this just yet.

**Comment by 0-wiz-0** [comment]
The fix for BSD make is quite easy, add:
````
man:
        @$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
````
The problem is that "%" is not defined as target name in BSD make, so we need to explicitly name the supported targets. I'm only interested in 'man' so I added that.

I know next to nothing about python packaging, I just reported my wish as a packager. If the man page is created and installed in a place where it's not found by default it's still better than if it's not installed at all IMHO, because you can just extend MANPATH and get it, otherwise you have to reinstall khard from sources.

**Comment by lucc** [comment]
The problem with hardcoding `man` as a target here, is that sphinx offers a bunch of targets. Check out `man help`.  I would like to avoid to hard code any number of those as it as they might change or a user might just need one that I did not hard code.

So the other possible solution could be to add gnu-make as a build time dependency to the pkgsrc build process.  What are other pkgsrc packages doing that need to build sphinx stuff?  I just had a short look at the wiki and the src tree but I did not see the makefile you use to install the package (I somewhere gathered that pkgsrc uses make, is that right?).  Can you share a link to that makefile?

For Arch Linux a bash script is used to build the binary package. It looks like [this for alot](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=alot-git) which is a package that also uses sphinx to build the man page. They have an array called makedepends (line 25, but for the arch build system gnu-make is an implicit dependency) and build the man page on line 46 and install it on line 64.

Would something like this be an acceptable solution for you?

**Comment by 0-wiz-0** [comment]
For pkgsrc, I've solved the issue (see https://github.com/NetBSD/pkgsrc/blob/trunk/misc/khard/Makefile).
This issue (for me) is just getting this to work for more people by default; or close it if you feel it's working well enough already.

**Comment by lucc** [comment]
Ok, so I decided to close this and consider gnu-make a build time dependency.
