### ISSUE TITLE
Cannot edit event's datetime as an all-day event

### ISSUE THREAD

**Issue by jlamoure** [scheibler/khard#223]
khal 0.9.10, apologies if this has been fixed or else doing something wrong. Using Debian Buster's package.

I cannot find a command arrangement that allows me to change the date of an all-day event without changing it into a time-ranged event. Likewise, I cannot change an event from time-ranged to all-day.

**Comment by lucc** [comment]
This is khard not khal.

**Comment by jlamoure** [comment]
Good god excuse me.
