### ISSUE TITLE
Add example config to /etc/khard in Debian package

### ISSUE THREAD

**Issue by jlamoure** [scheibler/khard#224]
Just a suggestion. I had to dig around to find the example config on the repo, as the link provided in [your 2014 blog post](http://eric-scheibler.de/en/blog/2014/10/Sync-calendars-and-address-books-between-Linux-and-Android/) is unfortunately down.

**Comment by lucc** [comment]
There is a config file in that post. Otherwise you might have to tell *which* link as I don't see any link to a config file there. Currently @scheibler is hard to reach so I doubt he will fix the post.

The config file for the current development version of khard can be found on the development branch: https://github.com/scheibler/khard/blob/develop/misc/khard/khard.conf.example . (As soon as @scheibler is back we have to change the default branch to develop, sorry there is nothing I can do about that right now).

**Comment by jlamoure** [comment]
I mean that the line

    wget -O ~/.config/khard/khard.conf https://github.com/scheibler/khard/raw/master/khard.conf.example

Goes to a dead link. That's ok if he can't fix that.

I suggest adding an example config to /etc/khard as that is pretty standard practice I believe and make it easier to do initial setup without needing to fish around for configs on the internet.

**Comment by lucc** [comment]
1. currently /etc/khard.conf is not read by khard. So putting anything there will have no effect
1. Khard is a program for contact management which is (in my opinion) a user tool. I do not know what benefit a system wide khard.conf would have. Which kind of address books can be configured on a system level? Are there even any address books present on any kind of unix/linux?
2. If on the other hand you are really asking to put an *example* file in /etc/khard.conf only for the user to read then I suggest to put it under /usr/share/doc/... instead. That seems to by quite standard as well. (From my system
```
$ ls /usr/share/doc|wc
586
$ ls /usr/share/doc/python* -d|wc
20
```
)
4. How do you even install random files with setuptools?  We also provide a zsh completion script which packagers can pick up. But we leave downstream packaging to other people (contrary to the title the debian package is not maintained here).

You are also welcome to help with #204 which has an item about a manpage for the config if I remember correctly.

**Comment by jlamoure** [comment]
You are correct, I don't mean for the file in that location to be used directly. Nor should it be, as obviously it must be changed per the user's case to do anything useful. Yes it looks like /usr/share/doc might be a better place for it.

And sorry for assuming the maintainers here have a hand in Debian's packaging.

I'm not sure what you mean by #4, as I hadn't heard of setuptools before now. I see it's used in setup.py. Maybe that's used for a pip install? I used apt.

If I interpret #201 linked from #204 correctly a man page has been written, but not for the config file. I'd love to pitch in sometime. If I find the time, I'll make a pull request?

Debian versions lag behind github repos (v. 0.13.0 khar is what I have) and I didn't worry about not finding a man page it since "khar --help" was as informative as I needed.

Sorry for the malinformed ramble.

**Comment by jlamoure** [comment]
Ah, f me.
``
$ tree /usr/share/doc/khard/
/usr/share/doc/khard/
├── AUTHORS
├── changelog.Debian.gz
├── changelog.gz
├── copyright
├── examples
│   ├── davcontroller
│   │   └── davcontroller.py.gz
│   ├── khard
│   │   ├── khard.conf.example
│   │   └── template_for_contact_creation.yaml
│   ├── sdiff
│   │   └── sdiff_khard_wrapper.sh
│   └── twinkle
│       ├── scripts
│       │   ├── config.py
│       │   ├── incoming_call_ended.py
│       │   ├── incoming_call_failed.py
│       │   └── incoming_call.py
│       └── sounds
│           ├── incoming_call.wav.gz
│           ├── outgoing_call.wav.gz
│           └── ringtone_segment.wav.gz
├── README.md.gz
└── todo.txt
``

**Comment by lucc** [comment]
@jlamoure you are always welcome to open pull requests :)

Setuptools is the library behind pip and the setup.py file. It is python specific. apt on the other hand is debian specific. That's only the first difference, there is whole lot more to say about the topic, but I won't :)
