### ISSUE TITLE
compress .wav files to .ogg

### ISSUE THREAD

**Issue by legrostdg** [scheibler/khard#228]
.wav files in `./misc/twinkle/sounds` are quite big. Would it be possible to compress those to .ogg (for example)? That would save space in the Debian package (and probably other places, too).

**Comment by lucc** [comment]
I do not use twinkle, @scheibler  does or did. So I can not tell you if twinkle can handle these. The whole twinkle and davcontroller stuff is very old code and might or might not work.

**Comment by guillemj** [comment]
Hi! When I briefly checked, it indeed didn't seem to support it, not even the new fork at http://twinkle.dolezel.info/. My proposal on that bug was to encode them as .ogg and add instructions on how to decode them when doing the setup, given that these are just examples for further integration.

**Comment by lucc** [comment]
If twinkle can not handle ogg files we should not use them.

What is *that bug*?

**Comment by guillemj** [comment]
Oh, sorry I had the impression @legrostdg had linked to it. *That bug* is the one I filed in Debian originally at https://bugs.debian.org/942416.

**Comment by lucc** [comment]
I would not want to encode the files as ogg because as you said twinkle does not seem to support it.  Feel free to do that in the debian package or just drop these examples.  I would prefer to drop them here as well because I don't use them and don't know if they even work correctly.  But I will have to wait for @scheibler to  be fair.

**Comment by lucc** [comment]
@scheibler please put the instructions in the docs and not the readme. I have moved most of  the documentation from the readme to the docs.

**Comment by legrostdg** [comment]
Maybe this should be re-opened, at least as a reminder, given @scheibler last comment?

**Comment by lucc** [comment]
For some reason I was assuming that "later" would be "later today" :(
