### ISSUE TITLE
Problem with editing existing contact in Python3

### ISSUE THREAD

**Issue by vbwagner** [scheibler/khard#238]
I've encountered following error attempting to edit contact with khard 0.13 using Python 3.7
and python3-vobject 0.9.6.1
(default setup for Debian 10)
```
$ khard edit some-contact
Traceback (most recent call last):
  File "/usr/bin/khard", line 11, in <module>
    load_entry_point('khard==0.13.0', 'console_scripts', 'khard')()
  File "/usr/lib/python3/dist-packages/khard/khard.py", line 1854, in main
    args.open_editor)
  File "/usr/lib/python3/dist-packages/khard/khard.py", line 1207, in modify_subcommand
    modify_existing_contact(selected_vcard)
  File "/usr/lib/python3/dist-packages/khard/khard.py", line 102, in modify_existing_contact
    old_contact.get_template()))
TypeError: __str__ returned non-string (type bytes)
```
It turns out that _get_string_field method  of the CarddavObject accesses
underlying vcard fields via getattr, not via public interface of vobject, and in some cases
vcard fields contain bytes objects, not strings, which is OK in python2, but breaks everything in python3.

I suggest to add type check and convert bytes to string in the_get_string_field in case of python3

**Comment by lucc** [comment]
hello @vbwagner can you provide a mini/dummy vcard so I can test it?

**Comment by vbwagner** [comment]
It seems that cause of problem is explicit specification of encoding and charset which was part of vCard 2.1 standard.  Python vobject module doesn't declare support of this version, but however, does some strange things when encountered it.

It is certainly vobject bug.

However. it might be good idea to have workaround around this bug. I'e. if version is 3.0 or above,  delete these parameters when card is read (since they are not  allowed in RFC 2456 and RFC 6350).

**Comment by lucc** [comment]
@vbwagner can you provide an example vcard non the less. If I am to code somthing to work around this I need an example. Otherwise I will lose this as an upstream bug.
