### ISSUE TITLE
Implement copy and move of contacts from one address book to the next

### ISSUE THREAD

**Issue by dvzrv** [scheibler/khard#24]
I think there are definite use-cases for copy (cp) and move (mv) of contacts from one address book to the next.

Copy would be especially useful for address books that are shared with many users.
Move would be especially useful when you want to clean up your address books, or the "status" of one of the contacts has changed.

**Comment by scheibler** [comment]
I see definite use cases for move and I've set that to my todo-list. But why would you want to hold
multiple instances of the same vcard? Using your example: why is it not enough to put the vcard
into the address book, which you want to share with others? And what about synchronicity? What
should happen to the local vcard version if someone changes it in the shared address book and vice
versa?

**Comment by dvzrv** [comment]
You mean for the copy command?
I saw the possibility to copy a version of a contact from your personal address book to an address book that you share with some other people (or even the other way round, doesn't really matter). In this case you wouldn't want to move the whole thing (most likely).
If the contact already exists, a merge should be tried, so you can "update" the contact with the details from your personal address book (the merge-try would also be a possible solution for the move command, if the vcard already exists).
I don't think it would be a good idea to take care of synchronicity with khard though (you would need some arbitrary lists for that, etc.).

**Comment by scheibler** [comment]
I've implemented the copy / move contact functionality. Please try out the latest version of khard
and have a look into the readme file too.

**Comment by dvzrv** [comment]
You rule! Will do over the weekend!

**Comment by dvzrv** [comment]
So far it works really well and I haven't encountered problems yet!
