### ISSUE TITLE
Must use full path to editor

### ISSUE THREAD

**Issue by willghatch** [scheibler/khard#25]
On different machines the executable for my editor may live in different places, but I don't want to change my config file for each machine.  I would really like to just put eg. `vim` rather than `/usr/bin/vim` and let it be found via the $PATH variable.

You can use `distutils.spawn.find_executable(editor)` to check if it exists, or just trust the user that as long as they've specified an editor that it will exist.  I'm happy to make a PR that does either of those, but I'm not sure what will be accepted.

**Comment by untitaker** [comment]
khard just shouldn't validate whether the executable exists. `subprocess` etc will do the right thing.

**Comment by untitaker** [comment]
But you probably want to apply `os.path.expanduser` on it.

**Comment by willghatch** [comment]
@unitaker that's a good point about os.path.expanduser.  But I think you're right that the best option is just not to validate -- people savvy enough to use a command line contact manager in the first place will probably be sure the editor they set is on their path.  It would be nice to just fall back on $EDITOR from the environment if it's not configured in khard.conf -- I bet 99% of khard users already set $EDITOR, and if it's not set properly they'll have more problems than just khard failing.

**Comment by scheibler** [comment]
Absolute paths for editor and merge_editor are not longer required (look at khard.conf.example).  If
you don't provide these options in the config file, khard will retrieve them from $EDITOR and
$MERGE_EDITOR shell variables.

**Comment by willghatch** [comment]
Nice, thanks!
