### ISSUE TITLE
khard should allow entering an address subset

### ISSUE THREAD

**Issue by dvzrv** [scheibler/khard#26]
It should be allowed to insert only a city or region in the address section, when doing a modify.
Atm khard throws "Error: address1 has no street" when there's a city, but no street.

For some contacts I don't exactly know where in a city/town/village they live, but it is necessary to know the city/town/village.

**Comment by scheibler** [comment]
I've removed the restrictions for the post address field. Please try again.

**Comment by dvzrv** [comment]
Nice! Works very well.
Removing Germany as the default country is a good choice, too!
