### ISSUE TITLE
[BUG] Card  from address book ... has no UID and will not be available.

### ISSUE THREAD

**Issue by pianoslum** [scheibler/khard#265]
Hi,
I synced my contacts using vdirsyncer and save it do ~/.contacts/32.vcf
In khard.conf I set path to ~/.contacts for addressbook [[allgemein]]. However, when starting khard --list I always get the following error:

Card  from address book allgemein has no UID and will not be available.
Found no contacts.

32.vcf looks good to me, here is a part with redacted info:

BEGIN:VADDRESSBOOK
BEGIN:VCARD
VERSION:3.0
FN:Joe Doe
N:Doe;Joe;;;
TEL;TYPE=CELL,pref:00123455677
PRODID:-//Open-Xchange//7.10.3-Rev13//EN
REV:20180904T174934Z
UID:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
END:VCARD
...

Setting debug=yes didn't help. Do you have an idea what might be wrong?

**Comment by lucc** [comment]
I can not reproduce this issue. Please see branch [test/issue-265](https://github.com/scheibler/khard/tree/test/issue-265). It seems to me that you did not post the exact file that produces the error. 

Please note that [documentation says](https://khard.readthedocs.io/en/latest/scripting.html#integration):
> For synchronisation programs it is important to note that khard expects the contacts in the configured address book directories to be stored in individual files. The files are expected to have a .vcf extension.

I assume that you have multible `VCARD` blocks inside one `VADDRESSBOOK` block in that file. These should probably be in seperate files without the `VADDRESSBOOK` wrapper.

**Comment by pianoslum** [comment]
@lucc thx for your answer.
You're right: I used singlefile-mode in vdirsyncer so there was just one file. Changing to "filesystem" solved the error.

I would suggest adding a test with a clearer error message. This could be as easy as checking for the presence of VADDRESSBOOK I think.

Thanks again :)

**Comment by lucc** [comment]
I would like to avoid testing for all kind of malformed stuff people can put in the khard folders. Also a complete `VADDRESSBOOK` entry is parsed by our underlying `vobject` library without errors and not even the type of the resulting object differs.  We would have to inspect the resulting object to check if it is a vcard or vaddressbook.

I would prefer to "document this away" so I commited 1b0c80a

**Comment by lucc** [comment]
https://khard.readthedocs.io/en/latest/scripting.html#id1
