### ISSUE TITLE
No matter what command: decoding with 'base64' codec failed (Error: Incorrect padding)

### ISSUE THREAD

**Issue by henrythemouse** [scheibler/khard#266]
I'm using:
Debian Siduction (sid based) 
khard and vdirsyncer installed from sid
python 3.8

No matter what command I try to use I get this error: decoding with 'base64' codec failed (Error: Incorrect padding)

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/base64_codec.py", line 19, in base64_decode
    return (base64.decodebytes(input), len(input))
  File "/usr/lib/python3.8/base64.py", line 546, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
``
I can only suppose that it might have something to do with the images stored in my vcf files. Is there a way to work around this issue?

**Comment by lucc** [comment]
I have no Idea how you get this backtrace out of khard. The file names in the backtrace seem to indicate that you do not run khard to get this error. Please provide a vcard (you can anonymize it) and the khard config and command that produce this error.

**Comment by henrythemouse** [comment]
**example Vcard:**

BEGIN:VCARD
VERSION:3.0
PRODID:+//IDN bitfire.at//DAVx5/2.6.3.1-ose ez-vcard/0.10.5
UID:wejg5tw6-t7p9-w0gk-lalo-0ue19taktmxq
FN:Ross Chris
N:Ross;Chris
TEL;TYPE=cell:666 555-9999
REV:20200303T143858Z
END:VCARD

**khard config:**

```
# example configuration file for khard version > 0.14.0
# place it under ~/.config/khard/khard.conf
# This file is parsed by the configobj library.  The syntax is described at
# https://configobj.readthedocs.io/en/latest/configobj.html#the-config-file-format

[addressbooks]
[[family]]
path = ~/.contacts/addresses
[[business]]
path = ~/.contacts/business

[general]
debug = no
default_action = list
# These are either strings or comma seperated lists
editor = mcedit
merge_editor = vimdiff

[contact table]
# display names by first or last name: first_name / last_name / formatted_name
display = first_name
# group by address book: yes / no
group_by_addressbook = no
# reverse table ordering: yes / no
reverse = no
# append nicknames to name column: yes / no
show_nicknames = no
# show uid table column: yes / no
show_uids = yes
# sort by first or last name: first_name / last_name / formatted_name
sort = last_name
# localize dates: yes / no
localize_dates = yes
# set a comma separated list of preferred phone number types in descending priority
# or nothing for non-filtered alphabetical order
preferred_phone_number_type = pref, cell, home
# set a comma separated list of preferred email address types in descending priority
# or nothing for non-filtered alphabetical order
preferred_email_address_type = pref, work, home

[vcard]
# extend contacts with your own private objects
# these objects are stored with a leading "X-" before the object name in the vcard files
# every object label may only contain letters, digits and the - character
# example:
#   private_objects = Jabber, Skype, Twitter
# default: ,  (the empty list)
private_objects = Jabber, Skype, Twitter
# preferred vcard version: 3.0 / 4.0
preferred_version = 3.0
# Look into source vcf files to speed up search queries: yes / no
search_in_source_files = no
# skip unparsable vcard files: yes / no
skip_unparsable = no

```
**The complete output from this command:**

khard show -u wejg5tw6-t7p9-w0gk-lalo-0ue19taktmxq
Filtering some problematic tags from /home/dave/.contacts/addresses/17CEC589-0332-4921-925E-28F63F6C4B3B.vcf
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/base64_codec.py", line 19, in base64_decode
    return (base64.decodebytes(input), len(input))
  File "/usr/lib/python3.8/base64.py", line 546, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (253909) cannot be 1 more than a multiple of 4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/khard/carddav_object.py", line 1511, in from_file
    vcard = vobject.readOne(contents)
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 1155, in readOne
    return next(readComponents(stream, validate, transform, ignoreUnreadable,
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 1120, in readComponents
    component.setBehaviorFromVersionLine(versionLine)
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 663, in setBehaviorFromVersionLine
    self.setBehavior(v)
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 170, in setBehavior
    obj.autoBehavior(True)
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 156, in autoBehavior
    self.behavior.decode(self)
  File "/usr/lib/python3/dist-packages/vobject/vcard.py", line 143, in decode
    line.value = codecs.decode(line.value.encode("utf-8"), "base64")
binascii.Error: decoding with 'base64' codec failed (Error: Invalid base64-encoded string: number of data characters (253909) cannot be 1 more than a multiple of 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/base64_codec.py", line 19, in base64_decode
    return (base64.decodebytes(input), len(input))
  File "/usr/lib/python3.8/base64.py", line 546, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (253909) cannot be 1 more than a multiple of 4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/khard", line 11, in <module>
    load_entry_point('khard==0.16.1', 'console_scripts', 'khard')()
  File "/usr/lib/python3/dist-packages/khard/khard.py", line 1150, in main
    args.addressbook = config.get_address_books(args.addressbook,
  File "/usr/lib/python3/dist-packages/khard/config.py", line 199, in get_address_books
    abook.load(queries[abook.name], self.search_in_source_files) # type: ignore
  File "/usr/lib/python3/dist-packages/khard/address_book.py", line 248, in load
    card = carddav_object.CarddavObject.from_file(
  File "/usr/lib/python3/dist-packages/khard/carddav_object.py", line 1516, in from_file
    vcard = vobject.readOne(cls._filter_invalid_tags(contents))
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 1155, in readOne
    return next(readComponents(stream, validate, transform, ignoreUnreadable,
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 1120, in readComponents
    component.setBehaviorFromVersionLine(versionLine)
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 663, in setBehaviorFromVersionLine
    self.setBehavior(v)
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 170, in setBehavior
    obj.autoBehavior(True)
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 156, in autoBehavior
    self.behavior.decode(self)
  File "/usr/lib/python3/dist-packages/vobject/vcard.py", line 143, in decode
    line.value = codecs.decode(line.value.encode("utf-8"), "base64")
binascii.Error: decoding with 'base64' codec failed (Error: Invalid base64-encoded string: number of data characters (253909) cannot be 1 more than a multiple of 4)

**Comment by henrythemouse** [comment]
As it turns out, I just noticed that first error line where khard seems to be having a problem with a specific vcf file, which happens to have an image a bit over 220K in it. I removed that vcf, khard found another, which I removed. I repeated this 4 times. After that, khard worked! Maybe there is something wrong with the images. I still have 2 vcf files with images over 220k and they are not causing any issues so far.

**Comment by henrythemouse** [comment]
When viewing the image data in mcview the first line between the 'good' images and the 'bad' images is distinctly different, not that I know that that would make a difference. Just noticing it.

```
Good image doesn't cause issue with khard:
PHOTO;ENCODING=B;TYPE=png;VALUE=BINARY:dataimage/pngbase64

Bad image crashes khard:
PHOTO;ENCODING=b;TYPE=png:data:image/png;base64,

```
First, there's the small 'b' verses the capital 'B'. The Value in the good one might 
correspond to the 'data' in the bad one, but they are different syntax.

Not sure any of this will help, hope it does though.

**Comment by lucc** [comment]
Ok that is much more helpful!

The start of the line in the vcards until the first colon is the attribute name and some tags or properties. After the first colon comes the value. And that is where the problem arises. You can check if the underlying vcard library can handle the card correctly:
```python
import vobject
file = "./whatever.vcf"
with open(file) as f:
    vcard = vobject.readOne(f)
with open(file) as f:
    raw = f.read()
print(vcard.serialize())
print(raw)
```

**Comment by lucc** [comment]
You can try to set the option `skip_unparsable = yes` until this is resolved. That should make khard usable in the presence of bad files.

**Comment by lucc** [comment]
I just hand crafted two vcard files after consulting the rfcs and have uploaded some tests: 5aa338d

The line that you mention as "does **not** cause problems" looks very strange to me. The other one looks quite good but might be missing a backslash escape for the comma. Are these vcards v3 or v4?

**Comment by henrythemouse** [comment]
> import vobject
> file = "./whatever.vcf"
> with open(file) as f:
>     vcard = vobject.readOne(f)
> with open(file) as f:
>     raw = f.read()
> print(vcard.serialize())
> print(raw)
> ```

Running this on a 'bad' vcf produces this output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/base64_codec.py", line 19, in base64_decode
    return (base64.decodebytes(input), len(input))
  File "/usr/lib/python3.8/base64.py", line 546, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./vcardtest.py", line 6, in <module>
    vcard = vobject.readOne(f)
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 1155, in readOne
    return next(readComponents(stream, validate, transform, ignoreUnreadable,
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 1120, in readComponents
    component.setBehaviorFromVersionLine(versionLine)
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 663, in setBehaviorFromVersionLine
    self.setBehavior(v)
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 170, in setBehavior
    obj.autoBehavior(True)
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 156, in autoBehavior
    self.behavior.decode(self)
  File "/usr/lib/python3/dist-packages/vobject/vcard.py", line 143, in decode
    line.value = codecs.decode(line.value.encode("utf-8"), "base64")
binascii.Error: decoding with 'base64' codec failed (Error: Incorrect padding)

```
Running this on a 'goode' vcf prints the vcard, no errors.

**Comment by henrythemouse** [comment]
> You can try to set the option `skip_unparsable = yes` until this is resolved. That should make khard usable in the presence of bad files.

Setting this in the conf file does not make khard skip the 'bad' parts of the vcf, the output is the same as before.

**Comment by henrythemouse** [comment]
> I just hand crafted two vcard files after consulting the rfcs and have uploaded some tests: [5aa338d](https://github.com/scheibler/khard/commit/5aa338dae371b4b20d5fc9f0e9c5615c373654ee)
> 
> The line that you mention as "does **not** cause problems" looks very strange to me. The other one looks quite good but might be missing a backslash escape for the comma. Are these vcards v3 or v4?

They all have the label: VERSION: 3.0

**Comment by lucc** [comment]
This (https://github.com/scheibler/khard/issues/266#issuecomment-648912889) indicates that it is an upstream bug. Please report it at https://github.com/eventable/vobject/ .

**Comment by henrythemouse** [comment]
Done

**Comment by lucc** [comment]
@henrythemouse thank you.

If you don't mind I would like you to try out [the new error-message branch](https://github.com/scheibler/khard/tree/error-message) I just created.  I hope to display a better error message to the user if a vcard like your 17CEC589-0332-4921-925E-28F63F6C4B3B.vcf is present.

**Comment by henrythemouse** [comment]
I don't know how I would do that, is there a patch or something? Do I need to do a pipsi installation? What's the best-easiest way to test this?

**Comment by lucc** [comment]
I assume you have some kind of Unix or Linux with git and python installed then you can do this (in a new folder that you can throw away later):
```sh
git clone --branch=error-message --depth=1 https://github.com/scheibler/khard/
cd khard
python3 setup.py build
python3 -m khard ls
```

**Comment by henrythemouse** [comment]
The output from "python3 -m khard ls":

```
 -----------------------------------------------------
 python3 -m khard ls
 
Filtering some problematic tags from /contacts/addresses/54E1EDDA-4349-47A1-A422-F0C8A94BF91F.vcf
Error: Could not parse file /contacts/addresses/54E1EDDA-4349-47A1-A422-F0C8A94BF91F.vcf
decoding with 'base64' codec failed (Error: Incorrect padding)
Error when parsing /contacts/addresses/54E1EDDA-4349-47A1-A422-F0C8A94BF91F.vcf in address book family: decoding with 'base64' codec failed (Error: Incorrect padding)
Use --debug for more information or --skip-unparsable to proceed

```
----------------------------------------------------------
The output from "python3 -m khard --skip-unparsabel":

```
python3 -m khard --skip-unparsable
Filtering some problematic tags from /contacts/addresses/54E1EDDA-4349-47A1-A422-F0C8A94BF91F.vcf
Error: Could not parse file /contacts/addresses/54E1EDDA-4349-47A1-A422-F0C8A94BF91F.vcf
decoding with 'base64' codec failed (Error: Incorrect padding)
Filtering some problematic tags from /contacts/addresses/17CEC589-0332-4921-925E-28F63F6C4B3B.vcf
Error: Could not parse file /contacts/addresses/17CEC589-0332-4921-925E-28F63F6C4B3B.vcf
decoding with 'base64' codec failed (Error: Invalid base64-encoded string: number of data characters (253909) cannot be 1 more than a multiple of 4)
Filtering some problematic tags from /contacts/addresses/454E3DD9-CF12-4413-8568-D62C57243931.vcf
Error: Could not parse file /contacts/addresses/454E3DD9-CF12-4413-8568-D62C57243931.vcf
decoding with 'base64' codec failed (Error: Incorrect padding)
Filtering some problematic tags from /contacts/addresses/130A48FE-CBDE-44A7-A90B-53E39458CD1B.vcf
Error: Could not parse file /contacts/addresses/130A48FE-CBDE-44A7-A90B-53E39458CD1B.vcf
decoding with 'base64' codec failed (Error: Incorrect padding)

4 of 23 vCard files of address book family could not be parsed.
Address books: business, family
Index    Name                             Phone                           Email
```
Followed by a list of all contacts except the offending ones.

**Comment by lucc** [comment]
Thank you, that is what I hoped for because it will give the user a better error message and a half way usable khard.
