### ISSUE TITLE
Phone2 on new contact states "Dresden"

### ISSUE THREAD

**Issue by dvzrv** [scheibler/khard#27]
When creating a new contact, the Phone2 type of that new contact states "Dresden".

That should probably be changed to "home" or "work", or be removed?

**Comment by scheibler** [comment]
It's only a placeholder and is intended to demonstrate, that you also may use custom labels for
phone numbers, email addresses and post addresses. If you ignore phone2, it will be skipped by the
parser. It's not necessary to delete that line manually. If "Dresden" is a bit confusing, I could
rename that to something else. Suggestions?

**Comment by dvzrv** [comment]
Ah, now I get it!
Still, I think "Dresden" is a bit too non-generic for most users :)
What about "home"/ "work"?

**Comment by scheibler** [comment]
Changed to "work".
