### ISSUE TITLE
Support for python3.9

### ISSUE THREAD

**Issue by Tonus1** [scheibler/khard#277]
Hi,
I unfortunately upgraded a bit too fast and broke khard. A bit annoying since my mutt relies on it.

I can rely on aliases but prefer much more khard !

**Comment by lucc** [comment]
Can you tell me what broke because it looks like the last [test run on python 3.10](https://travis-ci.org/github/scheibler/khard/jobs/721931462#L184) succeeded.

(Maybe also the python version you use, OS, how you installed khard, etc, just the normal stuff for a bug report.)

**Comment by lucc** [comment]
We are now also running the tests explicitly on 3.9: https://travis-ci.org/github/scheibler/khard

**Comment by Tonus1** [comment]
My bad ! I forgot I had a packaged version that superseeded the virtualenv I had just installed !
So sorry for the noise !
