### ISSUE TITLE
Why hardcode fields in list_contacts?

### ISSUE THREAD

**Issue by jonascant** [scheibler/khard#282]
For my personal use, i would like to parse contacts with khard and output not only the email adress, but also other specific fields. Why is the list --parsable function limited to name, phone and email? If there is no specific reason that i missed, i would like to try to make the fields user configurable. The hardcoded fields can be the defaults.

**Comment by lucc** [comment]
The historical reason is the format that mutt expects.

You can use the `ls -F` to specify the fields and you can also combine that with `-p`.
