### ISSUE TITLE
Potentially misleading project/package description?

### ISSUE THREAD

**Issue by bitfehler** [scheibler/khard#303]
Hey there,

I really hope this doesn't come across as rude, but I was really confused by the way this project presents itself. The brief description of your packages in both Alpine and Arch Linux is "Console carddav client", which I assume is taken from [here](https://github.com/scheibler/khard/blob/develop/doc/source/conf.py#L137). However, I think this description is more than just a bit of a stretch. CardDAV is a network protocol ([RFC](https://tools.ietf.org/rfcmarkup?doc=6352). You do state yourself in the first sentence of the README that this software operates only on the local machine, so I'd say it can be neither CardDAV nor a client?

I don't just want to complain, I am genuinely interested what your take is. I assume there is some reason why this is the way it is. Should you be up for it I would also offer to propose a patch with some updates to the docs?

Really sorry for being a bit pedantic here, I hope you understand. Just trying to minimize friction for folks assessing whether this project suits their needs.

**Comment by lucc** [comment]
Hey @bitfehler that's not rude :)

If the description somewhere can be improved, please do send a PR. For the packages in the distributions you might have t make a request there. I think the description in the man page originates from the short github project description.
