### ISSUE TITLE
--search searches base64 encoded PHOTO field

### ISSUE THREAD

**Issue by fauxmight** [scheibler/khard#31]
It would seem logical to ignore any PHOTO field when searching a text string to save execution time. Perhaps I'm overlooking a practical use case.

**Comment by scheibler** [comment]
That doesn't happen. Khard reads all vcard files in your contacts folder but parses only the
supported attributes like email addresses and phone numbers. All other attributes in your vcard file
(like photo) are skipped. This ensures the overall integrity of your contact data cause khard
doesn't remove or modify unknown fields which other programs could have created.

Then there is the print vcard function, which for example is called, if you want to view the details
of a contact. If you enter a search term, khard only searches within that contact details output
string.

So the only slowdown I can imagine could come from the vcard parsing library. I've tested the import
with about 50 contacts but only one of them with a photo included (about 70 kb in size) and
recognized no performance issues. But if you have much more contacts with photos of a higher
resolution, maybe this could lead to a bad user experience.

By the way: How do you come to the conclusion, that khard searches within the photo data field?

**Comment by fauxmight** [comment]
That's a fair question, and I haven't looked at the code.

I have a collection of 65 contacts. Each has a PHOTO field generated from a png about 200k in size.
`khard details -s [searchstring]` takes about 3-4 seconds wall clock time.
I have stripped the PHOTO field out of each contact and subsequent invocations of
`khard details -s [searchstring]` return instantly.

**Comment by scheibler** [comment]
Now I've tested with 40 contacts, each with a photo about 60 kb in size. Although I've noticed a
slight slowdown (about 0.5 seconds) it's much less than your delay. I could live with 0.5 seconds
but I understand, that 3 or 4 seconds are very annoying. Problem is, that I don't see a solution at
the moment. Maybe you could talk to the new vobject module developers at
https://github.com/tBaxter/vobject instead. Sounds like a more suitable address for that issue.

**Comment by fauxmight** [comment]
Hey thanks for looking into it. Have a great day.
