### ISSUE TITLE
khard mutt prints useless first line

### ISSUE THREAD

**Issue by DamienCassou** [scheibler/khard#32]
```
$ khard mutt
searching for '' ...
[...]
```

why is the first line sent to standard output instead of standard error? Because of this, programs using khard must filter the first line.

**Comment by scheibler** [comment]
The "mutt" action is mainly intended for address completion for that specific email client. Mutt
expects a single line message and then one tab separated email address and name per line. Look at
http://www.mutt.org/doc/manual/manual-4.html#ss4.5.

Alternatively you could try the "alot" action. Slightly different sort order but without the first
line. Or tell me your used email client and I could support that directly.

**Comment by DamienCassou** [comment]
No problem, thank you.

**Comment by mxmehl** [comment]
I have the same issue. I write my emails and edit their headers directly in vim (using QueryCommandComplete), so I don't need the first line (and it annoys if there's only one contact with the name).

Could you please add a parameter to cut off the first line and just show the results? Thanks!

**Comment by scheibler** [comment]
Did you try the --remove-first-line parameter?

```
khard email -h
```

Produces:

```
  [...]
  --remove-first-line   remove "searching for '' ..." line from parsable
                        output (that line is required by mutt)
```

**Comment by mxmehl** [comment]
> Did you try the --remove-first-line parameter?

No, I didn't see that parameter, sorry. Thanks for the quick reply!
