### ISSUE TITLE
Support for "CATEGORIES" field

### ISSUE THREAD

**Issue by GSI** [scheibler/khard#35]
Thanks for a great tool!

`CATEGORIES:` holds a comma separated list of strings. At least on Android these strings are then considered as **groups** the contact is a member of.

Examples:

`CATEGORIES:Friends`

`CATEGORIES:Business,Family`

It would be great if `khard add/modify` accepted entering those values accordingly.

(General side question: Is there a way to pass field values from the command line without having the editor open up?)

**Comment by scheibler** [comment]
Please try out the latest code from the master branch. That works for me.

I've played a bit with the category list and they really show up as groups in android's contacts app.
Didn't know that. But for syncing to android I use CardDAV-Sync. This tool creates a new account
for every address book and then the contacts app groups the categories for every account. So it's
not so helpful if you only could use groups within a single address book. Do you maybe have a better
solution for that?

At the moment you can't edit contacts at the console. Do you have an idea how this could look like?

**Comment by GSI** [comment]
Before switching to DAVdroid I used CardDav-Sync too. Both work the same in those regards.

As I use only two address books on the phone (business / private) I actually find this "restriction" useful.

Before switching to khard I used my own script to add contacts from the command line. The syntax I had decided for would translate like this:

`khard new 'First name' 'Last name' +155512345 cat1,cat2,cat3`

In khard the editor could still open up with the fields filled:

`khard new --open-editor 'First name' 'Last name' +155512345 cat1,cat2,cat3`

... or the fields could be named parameters (allowing for according wrapper scripts to achieve the above):

`khard new --open-editor -f 'First name' -l 'Last name' -n +155512345 -c cat1,cat2,cat3`

**Comment by scheibler** [comment]
I've added a method to create a new contact from the command line. Please have a look into the usage
section of the readme file and tell me, how you like it.

**Comment by GSI** [comment]
Great idea to use stdin. Keeps it flexible.

**Comment by GSI** [comment]
Maybe a switch to directly open the editor after creation via command line would still be valueable. Reasons:

* If creating a contact with the same fields as an existing one, running `khard modify` afterwards, would add overhead by prompting for contact selection.
* `khard` commands have a delay of > 1 sec (just here?), so this would spare some time. (Of course, that's not the final solution :))

Categories work perfectly fine by the way. Just tested. Thank you!

**Comment by scheibler** [comment]
I added the option --open-editor. But if you create a contact from stdin and use that, it makes your
terminal unusable (at least with vim as favorite text editor). You can fix the terminal output with
`stty sane` afterwards but that's the only workaround, I found.  Alternatively you may use the -t
option with a template file to create a new contact. That works. Please have a look into the empty
template file from the misc/khard/ folder for that.
