### ISSUE TITLE
Merge using sdiff and likely other "scroll-based" tools

### ISSUE THREAD

**Issue by GSI** [scheibler/khard#36]
Not really an issue, but I thought it me be good to have this little wrapper script documented:

    #!/bin/sh
    
    FIRST="$1"
    SECOND=`mktemp`
    mv -f "$2" "${SECOND}" && sdiff "${FIRST}" "${SECOND}" -o "$2"

**khard** requires the second file in the diff-operation to be modified in order to recognize a successful merge. However the file provided to **sdiff's** `-o` switch cannot be any of the source files. The above workaround handles this issue.

**Comment by scheibler** [comment]
I put your script into the misc/sdiff folder and documented it in the readme file. Thank you for sharing.
