### ISSUE TITLE
Bug: Escape sequences are interpreted

### ISSUE THREAD

**Issue by GSI** [scheibler/khard#37]
(At least) Android allows multi-line notes.

In the vcf line breaks are stored with a literal `\n`. When the according file is opened via `khard modify`, the `\n` are interpreted, thus adding unexpected lines in the editor and causing **khard** to fail saving any changes (`Error in input line 20: Malformed input`) at best, or wreaking (minor) havoc on the data (imagine this in the VCF: `NOTE:\nPHOTO;ENCODING=b;TYPE=jpeg:byebye photo`.

Technically **any** field can contain sequences like `\n`, so it would be good to **never** interpret anything coming from the VCF.

**Comment by scheibler** [comment]
Should be fixed now. Please try out again.

**Comment by GSI** [comment]
LGTM. Kudos for switching to YAML!
