### ISSUE TITLE
write_to_file is not atomic

### ISSUE THREAD

**Issue by untitaker** [scheibler/khard#41]
When khard opens the existing file X for writing, and vdirsyncer for reading, it may happen that vdirsyncer uploads a corrupted version of file X to the DAV-server that contains partially written content from the new version khard is writing.

To mitigate, please use https://github.com/untitaker/python-atomicwrites or use a similar implementation if you don't need Windows support.

**Comment by scheibler** [comment]
Done. Thank you.

**Comment by untitaker** [comment]
This seems fine, thanks.
