### ISSUE TITLE
Move to python-card-me?

### ISSUE THREAD

**Issue by DamienCassou** [scheibler/khard#44]
[Card Me](https://github.com/tBaxter/python-card-me) simplifies the process of parsing and creating iCalendar and vCard objects. It is a fork of the venerable vobject library, improved, updated, substantially rewritten for Python3 support, and with some proper unit tests.

**Comment by untitaker** [comment]
Interesting. I wonder whether vdirsyncer could make use of this as well, although its current parser has optimal performance for my trivial usecase...

**Comment by untitaker** [comment]
The first off-putting thing about this library is that it doesn't seem to follow PEP-8 naming conventions at all.

**Comment by scheibler** [comment]
Oh, good to know. When I have time, I will adapt khard. But at the moment it's not in the pypi
repositories (at least I didn't find it) and so it's harder to install. So I'll wait until that's
done.

**Comment by tBaxter** [comment]
@untitaker card me doesn't? Could you point me to the conventions, as I'm not familiar with them in PEP-8 (and thought I had a pretty good handle on PEP-8)

**Comment by untitaker** [comment]
I've only looked briefly, but IIRC some methods use camelCase (it's called something else, but you get the idea) instead of underscore_separation.

On 6 January 2016 14:55:37 CET, Tim Baxter <notifications@github.com> wrote:
>@untitaker card me doesn't? Could you point me to the conventions, as
>I'm not familiar with them in PEP-8 (and thought I had a pretty good
>handle on PEP-8)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/scheibler/khard/issues/44#issuecomment-169329014

-- 
Sent from my phone. Please excuse my brevity.

**Comment by tBaxter** [comment]
Reading https://www.python.org/dev/peps/pep-0008/#package-and-module-names it appears to be correct at the package and module level.

**Comment by untitaker** [comment]
Right, I mean [function names](https://www.python.org/dev/peps/pep-0008/#function-names) and [class names](https://www.python.org/dev/peps/pep-0008/#class-names) though.

There are the `pep8` and `flake8` packages on PyPI that would pedantically point out all formatting problems.

**Comment by tBaxter** [comment]
OK. As soon as my PEP-8 linter complains, I'll make changes.

**Comment by untitaker** [comment]
Which linter are you talking about?
