### ISSUE TITLE
Use `N` property instead of `FN` for sorting/listing contacts

### ISSUE THREAD

**Issue by lecagot** [scheibler/khard#45]
`khard` so far only uses the `FN` property of the _Identification Properties_ of the vcard specification. This is [the only mandatory property](http://www.w3.org/TR/vcard-rdf/). However some vcard applications don't use `Lastname Firstname` as the `FN` string, but vice versa:

```
FN:Firstname Lastname
N:Lastname;Firstname;;;
```

This is i.e. the case with `DAVdroid`. While listing your contacts are now sorted by the first name given in the `FN` property. In case you use other vcard applications and/or just have older vcards with `Lastname Firstname` as the `FN` string, `khard` mixes first names and last names when listing contacts.

It would be better if `khard` would use the `N` property, which clearly distinguishes between first and last/family names.

This way `khard` by default sorts by the family name instead of the first name (if `FN` is defined as `Firstname Lastname`), but could also be ordered to sort by first name.

**Comment by stweller** [comment]
I created a pull request that should fix this problem (see reference above).

**Comment by scheibler** [comment]
Done. Now it also sorts contacts with only a first or last name and organisations correctly. The
sort criteria "addressbook" got it's own command line option "--group-by-addressbook". You also can
set the sort and the group by address book options in khards config file. Please have a look into
the khard.conf.example file under misc/khard/.

**Comment by stweller** [comment]
Thanks! I can confirm this is working as intended.
