### ISSUE TITLE
Could not create the dictionary of the short uid's

### ISSUE THREAD

**Issue by gabm** [scheibler/khard#46]
v0.7.0 - specifically commit 527e1bae8d1d4dfb6fae45539fd30b0e3d09251f broke khard for me, any version before  is still working (currently using 0.7.0-b3). Whenever i start it, it just responds with: 

*Could not create the dictionary of the short uid's*

I am on ubuntu, using vdirsyncer and khard with mutt. What can I do to help u to debug the problem?

**Comment by scheibler** [comment]
Please try out the latest commit. I've made some changes to fix your issue. Despite that, I'am
interested in your contact uids for test purposes. Could you send me the uids per email?

Get uids:

```
grep -h -i -r "uid:" ~/.contacts > uids.txt
```

**Comment by gabm** [comment]
Thank you for fixing my issue so fast - the email has been sent to the contact information on your homepage...
