### ISSUE TITLE
Error when querying with spaces from Mutt

### ISSUE THREAD

**Issue by Markus00000** [scheibler/khard#49]
Completing recipients with `firstname lastn<tab>` in Mutt causes this error:

    To: firstname lastnusage: khard [-h] [-a ADDRESSBOOK] [-g] [--open-editor]
    [-r] [-s SEARCH] [--sort SORT] [-t TEMPLATE_FILE] [-u UID] [-v] [action]
    khard: error: unrecognized arguments: lastn

`muttrc` as documented in `README.md`:

    set query_command = "khard email --search '%s'"

No errors when querying khard directly:

    % khard email --search 'firstname lastn'
    searching for 'firstname lastn' ...

khard 0.8.1
mutt 1.5.24

Is this a khard or mutt issue?

**Comment by scheibler** [comment]
Yes, I'am aware of that. It seems, that mutt doesn't quote your search string automatically before
sending it to the address book application - although it's explicitly surrounded by single quotes
in the query_command option in mutt's config file. So khard gets the following:

```
khard email -s firstname lastn
```

Cause it's not quoted, lastn is treated as a new and unknown argument and that produces the error. I
don't know, how to prevent that. I've already spend some time with adding and removing single and
double quotes from the query_command string but had no luck so far.

Workaround: Either use "firstname lastn<tab>" or firstname*lastn<tab>.

**Comment by Markus00000** [comment]
According to [this bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=394532):

> It seems that mutt automagically quotes the %s argument and hence the single quotes here are harmful.

The following will correctly complete `firstname lastn<tab`:

    set query_command = "khard email --search %s"

You should probably update `README.md` accordingly.

**Comment by scheibler** [comment]
I could have sworn, that I've tried that before. But you are right, without the single quotes, it's
working fine. Thank you for pointing that out. I've already updated the readme file.

**Comment by lucc** [comment]
Can this be closed? (@Markus00000  NB the interface changed so you might need to change your muttrc on the next update of khard)

**Comment by Markus00000** [comment]
Yes, closed.

Thanks for the notice regarding the interface change.
