### ISSUE TITLE
Write correct VERSION field to vcard files after modify.

### ISSUE THREAD

**Issue by lucc** [scheibler/khard#50]
I assume that khard writes vcards version 4.0.

I imported some vcards that are version 2.1 (`cp some_2_1_card.vcf khard/adressbook/path/`). khard reads and searches these cards correctly (as far as I can see). But after an edit (`khard modify ...`) the card is written as a vcard version 3 but the `VERSION` field in the vcard still says `2.1`.

I would like khard to adjust the `VERSION` field to reflect the actual specification used in the vcard after it was written out from khard (after `khard modify ...`).

**Comment by scheibler** [comment]
The underlying vcard library creates vcards in version 3.0. But you're right: the old vcard version
number was not updated after modification. That should be fixed now. But beware, that the
transformation from vcard version 2.1 to 3.0 could cause some minor problems like missing type
values for phone, email and address attributes. So check your contact files after conversion.

**Comment by lucc** [comment]
thanks!
