### ISSUE TITLE
Traceback: Invalid syntax in "/usr/lib/python3.4/site-packages/khard/khard.py", line 675

### ISSUE THREAD

**Issue by clauseggers** [scheibler/khard#55]
```
Traceback (most recent call last):
  File "/usr/bin/khard", line 7, in <module>
    from khard.khard import main
  File "/usr/lib/python3.4/site-packages/khard/khard.py", line 675
    print selected_vcard.print_vcard()
                       ^
SyntaxError: invalid syntax
```

**Comment by scheibler** [comment]
At the moment khard is compatible to python 2.7 only but it seems, that you've run it under python
3.4. For example you could create a python 2.7 virtual environment like I've described in the khard
readme file. Besides that, you seem to run an older khard version - latest version is 0.8.1.

**Comment by clauseggers** [comment]
Of course, silly me. I had done some cleaning in my pip and moved khard over to v3 by accident. Thanks!
