### ISSUE TITLE
Bug: Saving contacts adds carriage returns to line endings

### ISSUE THREAD

**Issue by GSI** [scheibler/khard#56]
Saving a file that previously used *NIX style endings, converts it to Windows style (^M).

khard should maintain the style used in the original file.

**Comment by untitaker** [comment]
The vCard RFC requires `\r\n`-line endings, so it's not wrong for khard to correct them. This might be actually just what the library it uses does, and not something khard can change.

**Comment by GSI** [comment]
Confirmed :)

**Comment by lucc** [comment]
close?
