### ISSUE TITLE
Add release-tags, please

### ISSUE THREAD

**Issue by matthiasbeyer** [scheibler/khard#6]
Your `setup.py` file tells me that khard is in version `0.2.1`, but there are no release tags in the git repo!

I'd like to package khard for my favourite linux distro, but I guess without release tags, it is unreasonable hard for me to find the right commit for the actual version and installing from git is also an issue which would be solved with tags, as github provides `.tar.gz` archives for releases.

So, please, can you add git tags for your releases? Would be a pleasure for all packagers!

**Comment by scheibler** [comment]
Added a tag for release version 0.2.1. Anything else?

**Comment by matthiasbeyer** [comment]
Thanks a lot!
