### ISSUE TITLE
No module named 'helpers'

### ISSUE THREAD

**Issue by zedniss** [scheibler/khard#63]
I've been using khard in a python2 virtualenv for a while and it has been working great. Today I decided to replace it with a python3 virtualenv. I created the new virtualenv and installed khard. Now it fails with an import error:

```
$ ~/.virtualenvs/khard/bin/khard
Traceback (most recent call last):
  File "/home/user/.virtualenvs/khard/bin/khard", line 7, in <module>
    from khard.khard import main
  File "/home/user/.virtualenvs/khard/lib/python3.5/site-packages/khard/khard.py", line 11, in <module>
    import helpers
ImportError: No module named 'helpers'
```

If I open a python interpreter in the virtualenv and try to import the module, the same thing happens.

```
$ ~/.virtualenvs/khard/bin/python
Python 3.5.1 (default, Mar  3 2016, 09:29:07)
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import helpers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'helpers'
>>>
```

If I change into the package directory first, the import works:

```
$ cd ~/.virtualenvs/khard/lib/python3.5/site-packages/khard
$ ~/.virtualenvs/khard/bin/python
Python 3.5.1 (default, Mar  3 2016, 09:29:07)
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import helpers
>>>
```

It seems to be a path issue. How can I fix the khard executable?

**Comment by scheibler** [comment]
At the moment khard is not compatible to python3. But that's planned and will be included in the
next release. Please stay with your python2 virtual environment until then.

**Comment by zedniss** [comment]
Ok, thanks. I run khard, khal and vdirsyncer in the same virtual environment. I only tried upgrading since vdirsyncer is throwing warnings about their plan to drop python2 support. I'll stick with it for now and wait for the next release!
