### ISSUE TITLE
Show Birthday in ListView

### ISSUE THREAD

**Issue by johannes-darms** [scheibler/khard#64]
Hey,

I'd like to have the option to view the Birthdays of my Contacts in the ListView. This one is quite handy to export birthday list and get an overview about upcoming birthdays. From my first view at the code this is quite easy to implement and I would volunteer to do so. Is someone else interested in this feature?

**Comment by scheibler** [comment]
Done. New action: birthdays. Please try out version 0.10.0 from the master branch.

**Comment by johannes-darms** [comment]
Great Thanks, works for me! Sorry for this late reply.
