### ISSUE TITLE
Parseable output question

### ISSUE THREAD

**Issue by dvzrv** [scheibler/khard#66]
Is it possible to set the way parseable output is displayed?
I'd like to have it the way it was before: First name, last name <e-mail>, when I use it in mutt.

**Comment by scheibler** [comment]
Now it's linked to the "sort" parameter from the khard config file. If you specified "sort =
last_name", it's also used for the email and phone output. Default is first_name. I thought, that
the sort behavior should be consistent for every output.

But if you want to get output sorted by last name except for mutt, you could specify the ladder
explicitly in the mutt config file like:

```
set query_command= "khard email -p -s first_name %s"
```

**Comment by tsuflux** [comment]
It would be nice if khard provided a way to sort by the last name but still display the first name first.

**Comment by dvzrv** [comment]
@scheibler thank you! That solved my issue with this.
@tsuflux this way the first name is again displayed first (no more "last_name, first_name" behavior).

**Comment by tsuflux** [comment]
@dvzrv That is true however the output is not sorted by the last name which is my preferred way of showing a contact list.

**Comment by scheibler** [comment]
Why would you like to sort by last name and display names by first name and vice versa? Wouldn't
that be a bit chaotic? Do you mean like:


Sort by first name, display by first name:

- Arthur Black
- James Red
- Lisa White
- Paul Gray
- Zoe Blue


Sort by last name, display by first name:

- Arthur Black
- Zoe Blue
- Paul Gray
- James Red
- Lisa White


Sort by first name, display by last name:

- Black, Arthur
- Red, James
- White, Lisa
- Gray, Paul
- Blue, Zoe


Sort by last name, display by last name:

- Black, Arthur
- Blue, Zoe
- Gray, Paul
- Red, James
- White, Lisa

**Comment by Tonus1** [comment]
Second sorting is my favorite.

**Comment by tsuflux** [comment]
Yes, the second one (Sort by last name, display by first name) I prefer the most. This way people with the same last name (e.g. family members) are implicitly grouped while easy identification by their first name is given.

**Comment by scheibler** [comment]
Okay, I will separate the sort and display name option in the next release.
