### ISSUE TITLE
Missing v0.10.0 tag?

### ISSUE THREAD

**Issue by shtrom** [scheibler/khard#68]
I'm just trying khal out now, to replace pycarddav.

pip currently install version 0.9.0, but it seems 0.10.0 is out, looking at the commits here. However, there is no tag nor release available.

**Comment by scheibler** [comment]
Yes, 0.10.0 is classified as new version but it's not stable yet. I plan to release a new stable
version together with python3 support in the next days. Just use 0.9.0 from pypi so far or manually
install 0.10.0 from master branch via setup.py if you want to try out the latest program version.

**Comment by lucc** [comment]
@scheibler happy to hear that. Are you going to use #58 or #59 or do it yourself? If you want to use #59 I can fix the merge conflict and rebase it on master, just tell me.

**Comment by scheibler** [comment]
Currently I'am working at your pull request #59. Good start. Python3 seems to make some unicode
things much easier.  At the moment I rework the vcard parsing process a bit to fix #57. Hope that
I'am finished with that after next weekend. Then I will upload the new feature branch and contact
you again.
