### ISSUE TITLE
Mutt integration

### ISSUE THREAD

**Issue by drkh5h** [scheibler/khard#69]
When I try to use khard in mutt like specified in the README, mutt does not complete the query in the right way: When I press tab it completes to something like "user@domain.tldTestUserWork" and not for example to "Test User <user@domain.tld>" like it should.

**Comment by scheibler** [comment]
Please look here: https://github.com/scheibler/khard/pull/67#issuecomment-217871644

**Comment by drkh5h** [comment]
@scheibler Thank you very much, that solved it!
