### ISSUE TITLE
Support further BDAY formats

### ISSUE THREAD

**Issue by GSI** [scheibler/khard#72]
khard currently only supports this format: `BDAY:19960415`, while other applications may use further formats, in accordance to [RFC6350](http://tools.ietf.org/html/rfc6350#section-6.2.5):

             BDAY:--0415
             BDAY;19531015T231000Z
             BDAY;VALUE=text:circa 1800

These formats are currently ignored by khard, causing the impression that a contact has no BDAY set.

**Comment by scheibler** [comment]
We run into a vcard versioning problem here. As far as I understand, you're referring to
[RFC6350 / vcard 4.0](https://tools.ietf.org/html/rfc6350). But the python library vobject, which is
used by khard, only supports [RFC2426 / vcard 3.0](https://tools.ietf.org/html/rfc2426).

Vcard version 3.0 only accepts dates in the following three formats (section 3.1.5):

1. BDAY:1996-04-15 (already supported)
2. BDAY:1953-10-15T23:10:00Z (default datetime format, should be added although I don't know, why a
   birthday date should require a time instance)
3. BDAY:1987-09-27T08:30:00-06:00 (do you know, for what -06:00 stands?)

But that leads to a much bigger problem: How to deal with vcards with version != 3.0?

Vcard version 3.0 seems wildly used, although it's relatively old. For example if I create a new
contact on my Android phone and sync it to my notebook, the corresponding vcard holds the version
3.0. But nontheless it's likely, that we will see more and more vcards of version 4.0 in the future.
At the moment reading should be possible in general (some fields may be incompatible but the most
should work).  But during editing the vcard would be converted to vcard version 3.0 and data could
be lost. 

Unless the vobject library switches to vcard version 4.0 there is not much, that I can do about
that.  Only thing I can imagine is a warning message, which could be displayed, when the user wants
to modify a contact with vcard version != 3.0.

**Comment by scheibler** [comment]
Done.
