### ISSUE TITLE
the --parsable option writes name in format "surname, name" only

### ISSUE THREAD

**Issue by jpellegrini** [scheibler/khard#73]
Hello!

As I mentioned in the subject, the --parsable flag only prints "Surname, Name <email>".
It would be nice if it also did "Name Surname"... Although I can work around that by putting the contact's full name in the "name" field, and not use the surname field.

**Comment by scheibler** [comment]
You may change the name ordering with the -s / --sort [first_name|last_name] parameter. For example:

```
khard email --sort first_name --parsable search_query
```

Then you get:

```
searching for 'search_query' ...
search_query@example.org\tFirstName LastName\tType
```

Please have a look into khards example config file misc/khard/khard.conf.example too.

**Comment by jpellegrini** [comment]
Thta works perfectly! Thanks, and sorry for the noise...
