### ISSUE TITLE
khard as part of pimutils

### ISSUE THREAD

**Issue by gour** [scheibler/khard#74]
What do you think if making khard as part of [pimutils](https://github.com/pimutils) would provide some benefit to the both sides?

To me, khard looks as natural member. ;)

**Comment by scheibler** [comment]
Yes, I agree.

**Comment by untitaker** [comment]
Hey @scheibler, I can add you as a member if you want.

**Comment by scheibler** [comment]
Yes.

**Comment by untitaker** [comment]
@scheibler You should be invited... if you accept, you can transfer your repo I think.

Also check out `#pimutils` on freenode!

**Comment by untitaker** [comment]
Hello @scheibler, I wonder if you still have interest in adding khard to pimutils? I've sent you an invitation a while ago, you can accept it at https://github.com/pimutils

**Comment by varac** [comment]
?

**Comment by untitaker** [comment]
@varac I don't think it's happening, but not sure myself.

**Comment by varac** [comment]
@untitaker @scheibler: Why not ?

**Comment by untitaker** [comment]
I dont know

On 18 June 2017 19:31:58 GMT+02:00, varac <notifications@github.com> wrote:
>@untitaker @scheibler: Why not ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scheibler/khard/issues/74#issuecomment-309291166

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
