### ISSUE TITLE
same uid problem

### ISSUE THREAD

**Issue by gour** [scheibler/khard#84]
Hello, 

when I try to see my contacts I see:

```
$ khard details
3 of 355 vcard files of address book gour could not be parsed
Use --debug for more information or --skip-unparsable to proceed
```

It is strange that:

```
skip_unparsable = yes
```

 in my khard.conf does not work.

However, there is another problem:

```
khard --skip-unparsable details
The contact Foo Bar from address book gour and the contact Foo Bar from address book anothercontacts have the same uid a8df8007-3351-48de-8807-74b3e88dcf08@oc.domain.tld
```

Any hint how to resolve it?

**Comment by scheibler** [comment]
Saša Janiška <notifications@github.com> schrieb am 28.07.2016,  3:23 -0700:
>when I try to see my contacts I see:
>
>```
>$ khard details
>3 of 355 vcard files of address book gour could not be parsed
>Use --debug for more information or --skip-unparsable to proceed
>```

What does --debug say?

>It is strange that:
>
>```
>skip_unparsable = yes
>```
>
> in my khard.conf does not work.

Did you specify skip_unparsable in the vcard section (see misc/khard/khard.conf.example)?

>However, there is another problem:
>
>```
>khard --skip-unparsable details
>The contact Foo Bar from address book gour and the contact Foo Bar from address book anothercontacts have the same uid a8df8007-3351-48de-8807-74b3e88dcf08@oc.domain.tld
>```
>
>Any hint how to resolve it?

Set show_uids = no in the "contact table" section of khard.conf. But maybe you rather should fix
that same uid issue in your contacts directly (just change uid slightly).

**Comment by gour** [comment]
> What does --debug say?

```
$ khard --debug details
DEBUG:root:args=Namespace(action='details', addressbook=[], debug=True, display=None, group_by_addressbook=False, reverse=False, search_in_source_files=False, search_terms=[], skip_unparsable=False, sort=None, strict_search=False, uid='')
Error: Could not parse file /home/gour/prj/vf/vdir/contacts/collection/contacts/7bfc94e8-2a61-42a8-bcb9-de6d2153efee.vcf
'str' object has no attribute 'decode'
Error: Could not parse file /home/gour/prj/vf/vdir/contacts/collection/contacts/8a54307d-8dfa-4d3d-8773-1dcf1d7687df.vcf
'str' object has no attribute 'decode'
Error: Could not parse file /home/gour/prj/vf/vdir/contacts/collection/contacts/a65709f9-d5bf-4b61-849f-256cf04b640a.vcf
'str' object has no attribute 'decode'

3 of 354 vcard files of address book gour could not be parsed

The contact Foo Bar from address book...have the same uid a8df8007-3351-48de-8807-74b3e88dcf08@oc.domain.tld
```

Those un-parsable  contacts are the ones which contain photo and I see there is already issue #80 in regard.

> Did you specify skip_unparsable in the vcard section (see misc/khard/khard.conf.example)?

Nope, wasn't aware of it , now it does work. :-)

> Set show_uids = no in the "contact table" section of khard.conf. 

That helps, it was 'yes'.

> But maybe you rather should fix that same uid issue in your contacts directly (just change uid slightly).

OK. Will try that...

I bet it was when I did copy some contacts under Evolution from one addresbook to the other.

**Comment by untitaker** [comment]
@gour: How does your khard config look like? You should only point khard to the `filesystem`-type collections.

**Comment by untitaker** [comment]
(context is https://github.com/pimutils/vdirsyncer/issues/479)

**Comment by gour** [comment]
@untitaker it points to it...after manually changing few entries and re-syncing, everything is fine now

**Comment by untitaker** [comment]
If those entries represent different contacts it's fine, but if you're actually getting duplicate contacts in khard, something is very wrong.

BTW, `vdirsyncer repair` can take care of this.

**Comment by gour** [comment]
> If those entries represent different contacts it's fine, but if you're actually getting duplicate contacts in khard, something is very wrong.

Well, there **are** duplicate contacts in khard considering that me & my wife are sharing some, but the problem was **same* uid...manually fixing it, solved the problem.

> BTW, vdirsyncer repair can take care of this.

Of duplicate uids?

**Comment by untitaker** [comment]
> Of duplicate uids?

Yes.

**Comment by gour** [comment]
Ohh, that's something new...thank you for the pointer. ;)
