### ISSUE TITLE
Parsing error with gpg / pgp public KEY included

### ISSUE THREAD

**Issue by florianjacob** [scheibler/khard#86]
Some of my contacts have a public PGP key, which I store in my vCards. After some research, I found out this is exactly the same as #80, but with the base64-encoded `KEY` attribute:

```
KEY;ENCODING=b;TYPE=PGP:mQGNBFEGmToBDADDHQhox…
```

I hack-fixed the locally installed code by patching in a line similar to the photo ignore line, directly in the filter_photo_attribute method:

```
…
            if append_line and re.search("^key.*:.*$", line, re.IGNORECASE):
                append_line = False
…
```

which solved the problem. Probably one could also filter for `^.*;ENCODING=b;.*:.*$` more generally to wipe out everything base64-encoded.

Hopefully the upstream bug gets fixed soon, though, so that this won't be neccessary - I'm mainly posting this so that searching for issues with khard about KEY and PGP will return a result for others. :wink:

**Comment by scheibler** [comment]
florianjacob <notifications@github.com> schrieb am 01.08.2016, 16:13 -0700:
>Probably one could also filter for `^.*;ENCODING=b;.*:.*$` more generally to wipe out everything base64-encoded.

I should have done this in the first place but I didn't dare to.  But I think, the following regexp
is explicit enough to prevent false positive results (especially with the ; before and the ; or :
afterwards):

```
if append_line and re.search("^\S.*;encoding=b[;:].*$", line, re.IGNORECASE):
    append_line = False
```

For me, it's working. Could you also try that out please?

Thanks for your effort.

**Comment by florianjacob** [comment]
The united regex works for me & with my PHOTO / KEY cards as well. 😄 

The regex also seems sensibly explicit enough to me to rule out everything encoded as b, but not more. 👍

**Comment by scheibler** [comment]
Change added into the develop branch. Thanks again.

**Comment by florianjacob** [comment]
Hurray!Thanks for taking care, I'm running the develop branch now. 🎉

**Comment by lucc** [comment]
There has been an update to the base64 related code in vobject. Can you try if your issue also exists on khards master branch if you update vobject?

**Comment by florianjacob** [comment]
I just tried current khard master (wich is equivalent to 0.11.2, or did you mean another branch) with the current vobject 0.9.3 and I had no issues. I also commented out all try/except blocks around `self.vcard = vobject.readOne(contents)` so no base64 filtering should have been done, and it still seemed to work. :+1:

**Comment by scheibler** [comment]
Please also try to modify a contact with base64 encoded attributes like photos.

**Comment by florianjacob** [comment]
Oh! I did not realise you could actually do that this easily with khard, as I only needed it for read only display and then started to edit the vcard by hand. :sweat_smile: Cool feature!

Even with the base64 filtering fixes, I get this error when trying to modify a contact with base64 data:

```
Traceback (most recent call last):
  File "/usr/bin/khard", line 11, in <module>
    load_entry_point('khard==0.11.2', 'console_scripts', 'khard')()
  File "/usr/lib/python3.5/site-packages/khard/khard.py", line 1675, in main
    args.open_editor)
  File "/usr/lib/python3.5/site-packages/khard/khard.py", line 967, in modify_subcommand
    modify_existing_contact(selected_vcard)
  File "/usr/lib/python3.5/site-packages/khard/khard.py", line 129, in modify_existing_contact
    new_contact.write_to_file(overwrite=True)
  File "/usr/lib/python3.5/site-packages/khard/carddav_object.py", line 1415, in write_to_file
    vcard_string = self.vcard.serialize()
  File "/usr/lib/python3.5/site-packages/vobject/base.py", line 255, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/lib/python3.5/site-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/lib/python3.5/site-packages/vobject/base.py", line 993, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/usr/lib/python3.5/site-packages/vobject/base.py", line 255, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/lib/python3.5/site-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/lib/python3.5/site-packages/vobject/base.py", line 1001, in defaultSerialize
    obj.behavior.encode(obj)
  File "/usr/lib/python3.5/site-packages/vobject/vcard.py", line 152, in encode
    line.value = codecs.encode(line.value.encode(coding), "base64").decode("utf-8")
AttributeError: 'bytes' object has no attribute 'encode'
```

and it works fine for non-base64 contacts.

**Comment by scheibler** [comment]
florianjacob <notifications@github.com> schrieb am 02.09.2016,  4:47 -0700:
>Even with the base64 filtering fixes, I get this error when trying to modify a contact with base64 data:

Same here. Use vobject version 0.9.2 for now. That works.

**Comment by florianjacob** [comment]
Ok, I downgraded vobject again and now I'm hapilly editing PGP and image contacts with khard. :smile:

**Comment by lucc** [comment]
@florianjacob the upstream bug is resolved and a new version of khard is out. Do these solve it?

**Comment by florianjacob** [comment]
@lucc So the workaround got removed in the latest version? I just upgraded to the latest version 0.11.4 and can display my contacts with GPG key without exploding. 👍 😉  (the gpg key isn't shown on `khard show`, though, but I guess that's like it should be)

**Comment by scheibler** [comment]
Yes, at the moment the gpg key attribute is not supported by khard. Please open a new issue, if you think, that this feature should be implemented.

**Comment by florianjacob** [comment]
I currently don't have a use for that, my contacts just happened to have that property from another source.

Thanks for khard! Happily using it now. :smile:
