### ISSUE TITLE
ParseError when attempting a first run

### ISSUE THREAD

**Issue by hobarrera** [scheibler/khard#9]
```
Traceback (most recent call last):
  File "/usr/bin/khard", line 9, in <module>
    load_entry_point('khard==0.2.1', 'console_scripts', 'khard')()
  File "/usr/lib/python2.7/site-packages/khard/khard.py", line 101, in main
    args.action = Config().get_default_action()
  File "/usr/lib/python2.7/site-packages/khard/config.py", line 140, in __init__
    Config.__instance = Config.__impl()
  File "/usr/lib/python2.7/site-packages/khard/config.py", line 68, in __init__
    CarddavObject(addressbook['name'], addressbook['path'], filename))
  File "/usr/lib/python2.7/site-packages/khard/carddav_object.py", line 20, in __init__
    self.vcard = vobject.readOne(file.read())
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 1078, in readOne
    ignoreUnreadable, allowQP).next()
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 1031, in readComponents
    vline = textLineToContentLine(line, n)
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 888, in textLineToContentLine
    return ContentLine(*parseLine(text, n), **{'encoded':True, 'lineNumber' : n})
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 756, in parseLine
    raise ParseError("Failed to parse line: %s" % line, lineNumber)
vobject.base.ParseError: At line 14: Failed to parse line: X-MESSAGING/XMPP-ALL:mailkenoesevacuatro@gmail.com
```

**Comment by scheibler** [comment]
Hello,

Hugo Osvaldo Barrera <notifications@github.com> schrieb am 13.03.2015,  3:40 -0700:
>  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 756, in parseLine
>    raise ParseError("Failed to parse line: %s" % line, lineNumber)
>vobject.base.ParseError: At line 14: Failed to parse line: X-MESSAGING/XMPP-ALL:mailkenoesevacuatro@gmail.com

One of your contact files contains the attribute "X-MESSAGING/XMPP-ALL". That's for storing a Jabber
/ XMPP address. Khard uses the Python module vobject to parse the vcard files and only supports
vcard version <= 3.0 and it chokes at this particular attribute. So the error rather relates to the
vobject module than to khard.

Vcard is a bit messed up when it comes to extensions which were added later. I've googled a bit but
couldn't figure out, if "X-MESSAGING/XMPP-ALL" is a valid attribute or if the tool, which you used
so far produced an invalid vcard. But I found the vcard Wikipedia article with a list of widely used
extensions. For Jabber it's "X-JABBER". So if you change the line
X-MESSAGING/XMPP-ALL:mailkenoesevacuatro@gmail.com
to
X-JABBER:mailkenoesevacuatro@gmail.com
in your .vcf file, it's parsed correctly.

Khard had no error handling at this point and so it crashed. I've fixed that. Now if you start
khard, it tells you how many vcard files could not be parsed correctly.

Another point is, that khard currently only supports phone numbers, e-mail addresses and post
addresses. So even if you change the Jabber label it's not displayed. But if you request it, I could
add that to the program. At least your vcard file wouldn't be damaged, if you change something else
(for example the name or a phone number).

Hope that helps
Cheers
Eric

**Comment by hobarrera** [comment]
I'm running the latest from git, so I don't think it's totally fixed. :-/

In case you're interested, I believe this were generated with Thunderbird.

> Another point is, that khard currently only supports phone numbers, e-mail addresses and post addresses. So even if you change the Jabber label it's not displayed. But if you request it, I could add that to the program. At least your vcard file wouldn't be damaged, if you change something else (for example the name or a phone number).

As long as it's not deleted I don't care *too* much about seeing the attribute.

**Comment by scheibler** [comment]
Hugo Osvaldo Barrera <notifications@github.com> schrieb am 13.03.2015,  5:54 -0700:
>I'm running the latest from git, so I don't think it's totally fixed. :-/

Did you pull from git again after my last e-mail? I fixed khard's crash so that it should skip the
unparsable vcards. I tested that by adding the malformed line to one of my own contacts. Now it
tells me how many vcards were skipped and then lists all which were successfully parsed.

At the moment I can't fix the actual problem cause that's related to the vobject module. You only
could replace the particular lines manually (see my last mail).

If you still encounter crashes of khard, please send me the concerning error message.

Cheers
Eric

**Comment by hobarrera** [comment]
Oh, right. No, I had the latest from git prior to your comment.
What about ignoring just the ofending line? Is that too non-trivial?

If we have `Parse Error: At line 19:`, then read all lines except 19 and then feed that to vobject? Too hacky? :D

**Comment by scheibler** [comment]
Hugo Osvaldo Barrera <notifications@github.com> schrieb am 13.03.2015, 12:07 -0700:
>What about ignoring just the ofending line? Is that too non-trivial?
>If we have `Parse Error: At line 19:`, then read all lines except 19 and then feed that to vobject? Too hacky? :D

Yes that would be a hacky solution and a last resort...

With the Android contacts app I've added an ICQ and jabber id to one of my already existing contacts
to find out, how Android handles this. It created the following lines:
IMPP;X-SERVICE-TYPE=jabber:xmpp:nick@example.org
X-JABBER:nick@example.org
and the same for the ICQ number. When I later edit the address, a new
"IMPP;X-SERVICE-TYPE=jabber:xmpp:" line is added so we have two now. But the "X-JABBER" line is
changed. Then I deleted the "IMPP;X-SERVICE-TYPE=jabber:xmpp:" line and it still works with the
Android contacts app. So I guess, that the first line is only added for compatibility of some sort
and that the second is the actual one.

When I have a bit more time I will do some research about that and maybe create some kind of filter
to clean malformed lines in vcards.

Cheers
Eric

**Comment by hobarrera** [comment]
> When I have a bit more time I will do some research about that and maybe create some kind of filter to clean malformed lines in vcards.

Are they truly malformed, or is this an issue on vobject? I'd like to forward the issue properly (to lightning if it's invalid, or to vobject if it's valid but not being accepted).

Thanks.

**Comment by scheibler** [comment]
Hugo Osvaldo Barrera <notifications@github.com> schrieb am 14.03.2015,  4:10 -0700:
>> When I have a bit more time I will do some research about that and maybe create some kind of filter to clean malformed lines in vcards.
>Are they truly malformed, or is this an issue on vobject? I'd like to forward the issue properly (to lightning if it's invalid, or to vobject if it's valid but not being accepted).

Seems, that the "/" is forbidden in vcard attribute names. I've created a function, which filters
the problematic attributes and changes them to the standard ones. For example "X-messaging/xmpp-All"
becomes "X-JABBER". Works for me under Android 4.4. Please try, if your other contact programs also
accept that change (make a backup of your contacts before starting khard). And tell me, if you still
encounter parsing errors.

Cheers
Eric
