### ISSUE TITLE
debug parameter doesn't work

### ISSUE THREAD

**Issue by craftyguy** [scheibler/khard#90]
` clayton / computer /~  %  khard email -p aleth 

73 of 76 vcard files of address book contacts could not be parsed
Use --debug for more information or --skip-unparsable to proceed

 clayton / computer / ~  %  khard email -p aleth --debug          

usage: khard [-h] [--debug] [--skip-unparsable] [-v]
             {list,ls,details,export,birthdays,bdays,email,phone,source,new,add,add-email,merge,modify,edit,copy,cp,move,mv,remove,delete,del,rm,addressbooks,abooks}
             ...
khard: error: unrecognized arguments: --debug
`

**Comment by scheibler** [comment]
The options [-h], [--debug], [--skip-unparsable] and [-v] are global ones and therefore must be used
before the specified action (parameter ordering matters). So try to use:

```
khard --debug email -p aleth
```

Besides that, you should upgrade to the latest khard version (currently 0.11.2) to fix the contact
parsing issues.

**Comment by craftyguy** [comment]
Thanks, yea ordering resolved that issue.

BTW, I am still seeing the parsing issues on 0.11.2. debug output shows a bunch of these messages (all of them mention the 'decode' attribute) :

`Error: Could not parse file /home/clayton/.contacts/32/4d911cc6-81e1-4d45-8d97-94621b8fd6bb.vcf
'str' object has no attribute 'decode'`

**Comment by scheibler** [comment]
I thought, that I've fixed all of that errors already (prior related issues at #80, #86 and #87).
Anyway, could you send me one of the unparsable contacts for debugging purposes?

In the meantime you may use the --skip-unparsable parameter (if not too much contacts are affected):

```
khard --skip-unparsable list [search_name]
```

**Comment by craftyguy** [comment]
I've attached a vcf that is unparsable on 0.11.2:

```khard --debug email                                                                                                                                                                                                                                                             
DEBUG:root:args=Namespace(action='email', addressbook=[], debug=True, display=None, group_by_addressbook=False, parsable=False, remove_first_line=False, reverse=False, search_in_source_files=False, search_terms=[], skip_unparsable=False, sort=None, strict_search=False, uid='')
Error: Could not parse file /home/craftyguy/.contacts/32/4f1a1af4-ef9c-4dac-8e52-9e5128f95b5f.vcf
'str' object has no attribute 'decode'

1 of 1 vcard files of address book contacts could not be parsed```

[contact.zip](https://github.com/scheibler/khard/files/450925/contact.zip)

**Comment by lucc** [comment]
What version of vobject do you have installed (`pip show vobject`)? I think your error originates from vobject but is fixed in 0.9.3. So try to update that and report back.

**Comment by scheibler** [comment]
The vobject 0.9.3 release made it even worse. Prior to 0.9.3 the parsing error already occurred
during import. So I wrote a workaround function, which removes all base64 encoded attributes from
the vcard, parsed it and wrote them back after vcard export. Now the import works and so the
workaround function does not kick in. But the export of the modified vcard still fails with the
following error:

```
Traceback (most recent call last):
  [...]
  File "/home/eric/.virtualenvs/khard/lib/python3.5/site-packages/khard-0.11.2-py3.5.egg/khard/carddav_object.py", line 1414, in write_to_file
  File "/home/eric/.virtualenvs/khard/lib/python3.5/site-packages/vobject/base.py", line 255, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/home/eric/.virtualenvs/khard/lib/python3.5/site-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/home/eric/.virtualenvs/khard/lib/python3.5/site-packages/vobject/base.py", line 993, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/home/eric/.virtualenvs/khard/lib/python3.5/site-packages/vobject/base.py", line 255, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/home/eric/.virtualenvs/khard/lib/python3.5/site-packages/vobject/vcard.py", line 227, in serialize
    VCardTextBehavior.serialize(obj, buf, lineLength, validate)
  File "/home/eric/.virtualenvs/khard/lib/python3.5/site-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/home/eric/.virtualenvs/khard/lib/python3.5/site-packages/vobject/base.py", line 1001, in defaultSerialize
    obj.behavior.encode(obj)
  File "/home/eric/.virtualenvs/khard/lib/python3.5/site-packages/vobject/vcard.py", line 152, in encode
    line.value = codecs.encode(line.value.encode(coding), "base64").decode("utf-8")
AttributeError: 'bytes' object has no attribute 'encode'
```

@clayton craft: My base64 recognizing function does not find the photo attribute of your attached
vcard cause the encoding parameter is on a different line. Therefore I must improve the regexp but
with the open parsing issue of vobject version 0.9.3 I will wait a bit and see what happens next
there.  So you may use the previously mentioned --skip-unparsable option in the meantime.

**Comment by lucc** [comment]
Then we should maybe open a bug report upstream?

**Comment by scheibler** [comment]
Yes, I do it.

**Comment by florianjacob** [comment]
https://github.com/eventable/vobject/issues/39

**Comment by lucc** [comment]
@craftyguy the upstream bug is resolved and there is a new version of khard. Does that solve your issues?

**Comment by craftyguy** [comment]
@lucc yea, I think this one is resolved. I updated to the latest khard and vobject, and haven't noticed any issues with pulling up items like I was originally. Thanks for following up, y'all rock!
