### ISSUE TITLE
Warning about dropped data

### ISSUE THREAD

**Issue by lucc** [scheibler/khard#95]
When I create a new contact and enter a birthday in 1900 (which is my private way of telling me that i don't know the year of birth) the BDAY field is dropped from the final vcard.

I would like to have a warning about this. (This issue also serves as a reminder to myself if I want to work on this after some of my standing PRs)

The current solution is to use `khard source` to change the vcard version to 4.0 and use the `--mm-dd` syntax. Related to that I want to ask if there are plans to add a config option about the preferred vcard version. (also reminder to self)

**Comment by scheibler** [comment]
Yes, that's my solution too but it was buggy. Now it should work as expected.

I didn't forget your other stuff.

**Comment by lucc** [comment]
I found the undocumented option `vcard.preferred_version = 4.0` which makes this a little easier. (note for todo list/self: document it)

**Comment by scheibler** [comment]
Yes. If your other contact tools can process vcard 4.0 that's an option for newly created contacts.
But khard can't convert already existing contacts from version 3.0 to 4.0 cause it doesn't support
all vcard attributes and would make mistakes during conversion.

The option --vcard-version at least is documented at the help text table of the new action but I
will add a description in the readme file too. You also may have a look into
./misc/khard/khard.conf.example for preferred_version.
