### ISSUE TITLE
Update for vobject 0.9.3

### ISSUE THREAD

**Issue by protist** [scheibler/khard#97]
I'm [installing](https://aur.archlinux.org/packages/khard-git/) khard (git version) in Arch Linux. However, a recent update prevents it from working, presumably because khard wants vobject 0.9.2, and the current version in Arch is 0.9.3.

```
pkg_resources.ContextualVersionConflict: (vobject 0.9.3 (/usr/lib/python3.5/site-packages), Requirement.parse('vobject==0.9.2'), {'khard'})
```

FWIW I'm using the latest version of khard-git 0.11.3.r0.g95ef4cf-1.

**Comment by scheibler** [comment]
The vobject version was pinned due to issue https://github.com/eventable/vobject/issues/39. Khard
is confirmed to work with vobject version 0.9.2. If I hadn't pinned that version, other users would
run into the encoding errors. So please install khard within a virtual environment for now. When the
bug in the underlying library is fixed, I will make a new release and remove the version pinning.

**Comment by protist** [comment]
Thank you for that information. I'll just pin it locally too. Feel free to close this issue if you like. Cheers.

**Comment by jelmer** [comment]
The vevent issue (https://github.com/eventable/vobject/issuses/39) has an update that suggests it's been fixed.

**Comment by jelmer** [comment]
Err, https://github.com/eventable/vobject/issues/39 rather

**Comment by scheibler** [comment]
I've made some changes to the khard develop branch to support vobject 0.9.4.1. Seems to work fine.

Could anyone with base64 encoded contact attributes confirm that?

**Comment by protist** [comment]
I upgraded both and they seem to work fine for me too. I'm not really sure how to tell if I have base64 encoded contact attributes, though?

**Comment by scheibler** [comment]
Find contacts with base64 encoded attributes like photos with:

```
grep -r "ENCODING=B" ~/contacts
```

If you find a contact then try to edit it with:

```
khard ed <your contact>
```

vobject version history:

- 0.9.2:   Parsing fails
- 0.9.3:   Parsing should work but editing fails
- 0.9.4.1: Both should work

**Comment by protist** [comment]
That seemed to work fine. I edited the contact, and khard said `Modification successful`.

FWIW I had other contacts with photos that had `ENCODING=b` (lower case `b`).

**Comment by scheibler** [comment]
Thanks for testing. I'am glad, that this library issue seems to be fixed at last. I'll wait a few
more days, just to be sure and then create a new khard release, based on the current develop branch.

**Comment by scheibler** [comment]
Khard version 0.11.4 released.
